### ISSUE TITLE
Bug on meaning for Agathokritos (Fr& Engl)  : not judgment (visualization) but judge (edit).

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#162]

**Comment by Hippodamie** [comment]
Already # 151 !

**Comment by Hippodamie** [comment]
It still does not work for κριτ, see Agathokritos.
All has been perfectly changed in EDit (Meanings) [judge]] and saved, but the ancient meaning [judgment] remains in Visualization !
Thanks for your help.

**Comment by tuurma** [comment]
Reason for it, there were two versions of κριτ, differing in the way accents were input. As far as I remember, the roots baseForms were to have accents stripped?
```
    <category baseForm="κρῐ̄ν" ana="#sort #judgement">
        <catDesc>κρῐ̄(ν)</catDesc>
    </category>
    <category baseForm="κρῐ̄ν" ana="#sort #judge">
        <catDesc>κρῐ̄ν</catDesc>
    </category>
```

**Comment by edouardchiricat** [comment]
I think the bug comes from the fact that too many versions of kri(n) are
stored, Hence, the necessity to be able to delete the wrong ones.
In fact, what happens is that you call the κρῑ(ν) root, but it's always the
κρῑν one that fills the form (why?!).
The modifications were made in κρῑν, but in Visualisation appears κρῑ(ν)
with its values. (Again, why?!)
I think it is paramount now to have the possibility to clean the roots that
are either deprecated or have been wrongly input. Not only because the
forementioned error; in the future, the people who will encode will find be
extremely confused by the number of forms that exist for the same root (for
krin there are four now).

Édouard

**Comment by Hippodamie** [comment]
The only to keep is:
> <category baseForm="κρῐ̄ν" ana="#sort #judgement »>    BUT, here meaning is to modify to : ana="#sort #judge">
>         <catDesc>κρῐ̄(ν)</catDesc>


Many thanks, Magdalena and Edouard..
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Just a thing, to be clear, about the fact that modifications will happen very often during all the progress of the work (around 35000 names) and make necessary for us to be able to delete and rewrite:
the EDit interface has to be a collaborative space, where some people will edit and some others, or even sometimes the same person, will come after and change things, which could happen in every column and for every information. because our search is above all new. Sometimes, we will only find the solution one month after and change several informations then. Change could happen 2 or 3 times, no more after the beginnings where we still discover problems that we did not think about.
And the editors could be 5 to 10 and the revisors 2 to 5, no more.

Best regards.
Have a good day.
The Searching case and alphabetical order are a must : many thanks !
Sophie

**Comment by edouardchiricat** [comment]
I solved this one using a trick. But we badly need a way to delete multiple versions of the same root. For κριν there are 4, we need only one, the good one.

**Comment by tuurma** [comment]
Thanks @edouardchiricat for quick fix, I will work on feature to browse/edit roots soon. Closing this one.
