### ISSUE TITLE
Add new "author" field for the names already input.

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#211]

**Comment by edouardchiricat** [comment]
What is written in the field author in entries for new names doesn't show up on the Visualization page.

**Comment by Hippodamie** [comment]
Dear Magdalena,

Many thanks for your new Senses function.

Could you, please, make possible to see 500 roots in the same page and 500 senses ?

Have a nice day.
Best,

Sophie

**Comment by Hippodamie** [comment]
Thanks for your help !
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Many thanks for your help.

Not so easy as before to load when I want to enter or refresh: it is a problem for me because I have only for working a lap-top with more memory, nothing else. It is as if I need a very good connection, which is a problem when I am not at home and on Eduroam, for example, which is the case everywhere in my university.

What to do ?

Best,

Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Could we, please, add: 
Panhellenic (after Pamphylian).
The 8 following labels at the end of the list:
Greco-Anatolian
Greco-Egyptian
Greco-Etruscan
Greco-Iranian
Greco-Latin
Greco-Phrygian
Greco-Semitic
Greco-Thracian.

Deleting Latin itself.

Many many thanks.
Good night.
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Here below are the French translations added.
Could you please add also the new label:         Greek?/Grec?
Many thanks.

Have a nice day.
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

We are oblige to put the author name of the ancient Source in the same box as the name of the book he has written, otherwise we do not see the author name in the visualisation window..
For example, for Babelyka, I had to put Iamb. (author), VP (reference) in the same box, and could not put Iamb. in the box Author.

Why is it so ?
Could you improve it or do we have to input in the way I did ?

Have a nice day.
Thanks for your help.
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena and Edouard,

I am blocked on the edition window of Babyrias and cannot work since last Friday and then was not able to revise the names Edouard has edited on Friday.
I would like also that the names I or Gerard Genevrois edit have the Att#, Gender & Period informations automatically loaded as it usually happens for Edouard.

Many thanks for your help, Magdalena.

Have both a good week.
Best,
Sophie

**Comment by edouardchiricat** [comment]
Maybe because the second interpretation doesn't have certainty=low in
Babyrias?

Édouard

**Comment by Hippodamie** [comment]
Bonjour, Edouard.
Merci de ton aide.
J’ai du mal aussi avec « save » la plupart du temps. 

Tu n’as pas répondu à la question concernant les fonctions att#, genre et période? Sont-elles automatiques pour toi ?

Bien à toi,
Sophie

**Comment by edouardchiricat** [comment]
Chère Sophie,
Désolé, je ne vois ton message que maintenant.
Moi aussi j'ai des problèmes pour sauvegarder. Il faut que je clique
plusieurs fois et j'ai des messages d'erreur systématiquement.
Bien entendu, att#, genre et période sont renseignés automatiquement, mais
pas systématiquement.
Bien cordialement,
Édouard

**Comment by Hippodamie** [comment]
Merci, cher Edouard.
Je ne comprends pas cette absence de systématisme.
Bon travail.
J’espère que tu es en forme.
Bien à toi,
Sophie

**Comment by tuurma** [comment]
Pulling in information about the name (number of attestations &c) was already registered as #221, let's continue discussion there.
For other problems mentioned here I opened separate issues today.
Please, try to register new issues where necessary and comment in appropriate threads, it will make our lives easier.

**Comment by Hippodamie** [comment]
Sorry for that, dear Magdalena, you are right. Thanks for what you did today !
Best,
Sophie
