### ISSUE TITLE
Bug on Sosangelos: the sub-morphemes window does not work anymore. Thanks for your help!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#219]

**Comment by tuurma** [comment]
Sorry, I cannot reproduce this. Could you possibly check and reopen if problem persists?

**Comment by Hippodamie** [comment]
But Edouard has a normal morphem sub-form window for ανγελ: how is it possible ?
For me, it just looks as you can see

**Comment by edouardchiricat** [comment]
Sophie is right. I was looking at the first root, but now I see that there
is a problem with ανγελ: It has lost its translations and the LGPN-Ling
morpheme sub-form window doesn't allow to input them anymore. There are
just three cases 'type to search'.
The problem is wider: the root lost its translations in all the 20 names
where it appears.
I encountered the same problem in the past, but I solved it by deleting the
"damaged" root everywhere and re-typing it from scratch. Now, doing this
for 20 names is still feasible, but when we will have 100 or 200 names with
such a damaged" root, it will be impossible to proceed in this way.
Could you please have a look, Magdalena, and try to find what happened, in
order to avoid this bug in the future? I suppose that all began when Sophie
wanted to modify the meanings of ανγελ.
Thank you.

Édouard
