### ISSUE TITLE
Add .csv export facility

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#22]
Please add the possibility to export all or a group of entries into a .csv file

**Comment by patczar** [comment]
I can do this. I would write it in Java, unless anybody has a different suggestion.
There is a good CSV library in Apache Commons, but it would be the first external dependency of this project (involving Ivy downloads etc.). May I use it?

**Comment by adamretter** [comment]
@tuurma I am not sure why you guys assigned me? What is it you want to know?

**Comment by tuurma** [comment]
@edouardchiricat draft version of csv export now available, we'd welcome more detailed specification for this

**Comment by edouardchiricat** [comment]
The result of the csv export is not very nice or usable:
​

Édouard

**Comment by edouardchiricat** [comment]
And I have to open it with numbers if I want to have proper Greek; Excel
displays gobbledygook...

Édouard

**Comment by patczar** [comment]
> The result of the csv export is not very nice or usable
Hello Édouard, nice to meet you, and thanks for constructive feedback at the beginning.. ;)

Going to details... I made some effort to send appropriate HTTP headers, so that the data is recognized as CSV and given a *.csv file name (for me it's "nice", but it's subjective) and it seems to work properly on Firefox+LibreOffice.
I don't have Excel on my computer and I wasn't able to test on it. So thanks (really) for identifying the issue with opening in Excel. We're dealing with such details, that the Polish version of Excel uses semicolons, while the English version uses commas. And I used ";" because I knew it from Polish Excel. IDK what about the French one, but chances are that it's analogous to Polish, because we have the same number formatting rules.
I'm committing a version with commas in the next PR, you can try it.

The Greek letters issue may be related to the default font setting in Excel. A Unicode font is required, and it is not possible to specify fonts in CSV. Does the CSV from this version
http://clas-lgpn2.classics.ox.ac.uk
show properly?

Some columns are empty because of lacking data and the whole thing is a "draft", which means that we'd like to hear what columns are expected. The link on the front page can also be changed into something more elegant.

Best regards, Patryk

**Comment by edouardchiricat** [comment]
Dear Patryk,
These are the columns one should expect:

​
​Thank you so much for your work. I was aware that the file was just a
draft.
With all best wishes,

Édouard

**Comment by patczar** [comment]
Thanks for quick reply. I'm afraid your message has been distorted by github or something, because I can't see the "columns" you've probably wrote or copied here (empty line after "expect:")...
Magda, can you read the whole message?
