### ISSUE TITLE
Bug on Laiagos: HPN details does not want to appear, but are present in the EDit window. Thanks !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#220]

**Comment by edouardchiricat** [comment]
Dear Sophie,
This is probably my mistake. I put the page numbers in the new "author"
case instead of the case "details". Now it's fixed.
Nevertheless, there is still a bug: the information input in the "author"
case is not displayed on the Visualization page.
This issue (#220) should be closed now.

Édouard

**Comment by tuurma** [comment]
Thanks, Édouard, I'll upload a fix for the Visualization part later today.

**Comment by edouardchiricat** [comment]
Dear Magdalena,
Could you leave the visualization of the title (=reference) as it is, in
italics, and render the content of the box Author in normal letters?
Thank you.

Édouard

**Comment by edouardchiricat** [comment]
...And in Visualization the author should precede the reference (=title).

Édouard
