### ISSUE TITLE
Add multi-user accounts

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#23]
Add multi-user accounts with passwords and different privileges once the work on the editing tool is over for good. (And probably after migrating it to the Classics server)

**Comment by tuurma** [comment]
First version up now

**Comment by edouardchiricat** [comment]
So, we should receive login names and passwords?

Édouard

**Comment by tuurma** [comment]
Yes, but bear with me a bit longer as I test this, I'll be in touch about
passwords via email.

**Comment by edouardchiricat** [comment]
No worries!

Édouard

**Comment by Hippodamie** [comment]
Dear Magdalena,

How will it work ?
Because I have somebody almost ready to begin to edit new names.

Many, many thanks !
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena, dear Edouard,

I do not have any access to the Edit Interface to revise Edouard’s work : I do not see anymore the labels « edit » in both sides of the lines !
Best,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

bear with me a bit longer, we are just testing this facility with Edouard
and I hope to send you your personal username later today. You mentioned
new people starting soon, please let me know their names via email and I
will set up accounts for them as well.

**Comment by Hippodamie** [comment]
Very well !

I need now a « read only » account for Laurent Dubois, Gérard Genevrois and Claire Le Feuvre. And probably Robert Parker, Richard Catling and JS Balzat if they do not want and do not have time to edit themselves (I will ask them).
In mid-April, I would like for Gérard Genevrois and Claire Le Feuvre their accounts to be changed to  Edit accounts (for a long time, more than a year, maybe permanent fir the 5 following years).

At the end of May, I will need Edit accounts for two other post-doctoral students. But only for a limited time (1, to 4 months, just the time they work for the project). I do not have already their names. How will I be able to end their Edit access, at the end ?

Another step for access for new people will be next October.

I come back with another question in another message.

Many thanks.
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

1.

I forgot in the previous email :

If LGPN-Ling gets fundings from french Agence Nationale de la Recherche from next October, I will be obliged to give access to the data to a French service of stock and security of data called Huma-Num (http://www.huma-num.fr) : because we get the fundings only if we secure the data also by them.
So, I think they will need an account also (but not to edit), just to keep or stock the data and having them especially in xml language so that they could convert them in the future, if it is necessary, so that our data could be read for ever...  

Do you see how you could give access and what kind of access you could give to them ? 
Because, it would be important to save the data by them also, for example every week or every month.

2a. When do you think you will be able to make cvs working ? Another important way to have another type of copy of the data. And also for the book we will publish using the data. 

2b. For our work with Edouard, it is important also that I be able to quickly identify which new names have to be revised after a week of Edouard’s work : a possibility is for him to make a copy of all the names of the week, in the alphabetic order, in a special document Word or cvs, if cvs is a quite friendly looking format.

That is all.
Please, do not forget to announce me when I can again Edit, to revise Edouard’s work of the previous week !
many thanks,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Is it normal that the lgpn2 Database does not work as it did ?
I ask for *βουλ* (more than 1985 results), but no data are fetched.
We cannot work in linguistics if we do not have the truncation function (we use it all the time): and it seems it does not still exist in the new Lexicon of Greek Personal Names. 

Will we have the function truncation in the new database search ?
Will we keep the ancient lgpn2 alive before the new one is working, and even after ?

Many thanks,
Sophie
