### ISSUE TITLE
Please, Magdalena : G. Genevrois can do anything. Function saving is for him impossible... Thanks for your help. Sophie

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#264]

**Comment by tuurma** [comment]
I'm trying to nail down the reasons, my apologies for the inconvenience, I
will keep you informed.

**Comment by tuurma** [comment]
After recent server crash the server was restarted without a certain configuration setting on which caused problems for names containing macrons (which is a majority of them). The crash itself was most probably due to the resources allocated to this instance being a bit too small for the amount of data we have, so it was now significantly increased in order to prevent similar situations recurring. Apologies again for the inconveniences it caused.

**Comment by tuurma** [comment]
After recent server crash the server was restarted without a certain configuration setting on which caused problems for names containing macrons (which is a majority of them). The crash itself was most probably due to the resources allocated to this instance being a bit too small for the amount of data we have, so it was now significantly increased in order to prevent similar situations recurring. Apologies again for the inconveniences it caused.
