### ISSUE TITLE
Big problems with saving a root after server down

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#268]

**Comment by edouardchiricat** [comment]
In Μιμναγόρης, I've tried half an hour to save the root μιμν: The meanings didn't shw up, I have tried to re-enter it at least ten times, opening new windows, logging-in and logging-out, and at the end the meanings are : remain, tarry, tarry, tarry, tarry. I do not dare to change anything now.
But this means that the root saving problem which didn't show during the last three weeks, has risen from the dead.

**Comment by tuurma** [comment]
I tried and normally I can save the root without problem. In one case, though, entering the new root I've corrected it's form between the main form ant the root subform, the root was saved under the corrected form (as expected) but the main form wasn't updated accordingly, which led to 'broken' connection between the name and the root meaning.
Btw, I fixed Μιμναγόρης, there was a duplicate entry for the meaning 'tarry' and I need to think how did it happen, because, in theory, it should never happen, but it obviously did...

**Comment by Hippodamie** [comment]
Αgain a problem on the same Mimnagores.
PLease, Magdalena, "tarry" is to delete. The good order is : remain, await, hold out.
Many thanks.
Best,
Sophie

**Comment by edouardchiricat** [comment]
You see, dear Magdalena, this is the kind of bug that shouldn't
happen/exist at this stage of the project. Thank you for finding a way to
fix it.
With all best wishes,
Édouard

**Comment by edouardchiricat** [comment]
You see, now we hava on the visualisation page : 'remain, await, hold out,
hold out...' It happens again....

Édouard

**Comment by tuurma** [comment]
I'm implementing a fix.

**Comment by edouardchiricat** [comment]
I have input a new root, everything went perfectly, but now both root and meaning do not appear on the visualisalissation interface

**Comment by edouardchiricat** [comment]
I have input a new root, everything went perfectly, but now both root and meaning do not appear on the visualisation interface

**Comment by edouardchiricat** [comment]
The name is Pythangelos.

**Comment by tuurma** [comment]
it's due to normalization issues fixed today with cd57478b91c569d12eee8d23f01663ed5746abe3, I'll update the version on the server this evening after everyone's has finished work

**Comment by edouardchiricat** [comment]
Thank you, Magdalena!

Édouard

**Comment by Hippodamie** [comment]
Dear Magdalena and Edouard,

To input combined Greek Unicode letters rather than separately tape the diacritics + letter : 

we can do it editing the name in its Greek form and even editing the root, BUT concerning the Greek quotations we add in Lexis when we have the time to search and add it, it is impossible because too much time consuming. Since every Greek word has, for example an accent, we cannot take the time to search for each word the Greek letter with its good accent in a special list, whereas when we put them separately, we can do it directly taping on our keyboard.

Is it a problem for the sole quotation if it is written without combined Unicode characters ?

Best,
Sophie

**Comment by Hippodamie** [comment]
Cher Edouard,

Rien à modifier pour Pythaggelos, qui était déjà ds la base. Il y a bien à distinguer πυθ de πῡθ, il y aura toujours à hésiter entre les deux, et dans le doute, à suivre Bechtel.

Merci. Bien à toi,
Sophie

**Comment by edouardchiricat** [comment]
There is absolutely no problem for the quotations. What Magdalena is
interested in, is to have the Greek for of the name written with diacritics
and letters combines in one character, in order to link it to the same
canonic form in the prosopographic part. And also, the Greek form is the
unique identifier of a name, so it has to be written in the same way
everywhere.

Édouard

**Comment by tuurma** [comment]
Dear Sophie,

I've introduced the unicode normalization for all text in the input form,
which should take care of cases of combining marks vs single Unicode
characters, so no problem with quotations whatsoever. For names where
apostrophes were used in place of combining marks before capital letters,
as discussed on Friday, I'm putting in place an additional normalizing
facility. The mechanism is ready, but perhaps it doesn't cover all
combinations yet. I'll upload the new version on server tonight.

**Comment by Hippodamie** [comment]
Dear Magdalena and Edouard,

Many, many thanks to both of you.
No work anymore on LGPNLing tonight. So you can do what you need to do, Magdalena.
Good night.
Best,
Sophie
