### ISSUE TITLE
autocomplete fields not working in newly added repeats

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#274]
on adding a new 'segmentation' section, autocompletes on root and constituent fields are not active

![screenshot 194](https://cloud.githubusercontent.com/assets/449468/15928634/f81a34d6-2e3f-11e6-8284-e51980ef6eac.png)

**Comment by edouardchiricat** [comment]
Well, I have just tries with δᾱμ and if I tape δα, δᾱμ does not appear on the list.
Another BIG problem has to be solved, now that we have a big number of roots already input: they should be organised alphabetically (according to the greek alphabet, of course) One has to read an entire list of ten or 20 roots in order to find the one he wants.

**Comment by tuurma** [comment]
Ok, thanks for pointing that out, the sorting should be less complicated
for roots than in general, as here we don't have all this fancy accents
with special rules.

For search, I'll just make it ignore all macrons etc, which should solve
the problem.

**Comment by edouardchiricat** [comment]
Please make it ignore also the initial Latin 'h' that marks the aspiration.
