### ISSUE TITLE
Hi, Magdalena ! Sub form window does not open. No way to Edit a new Root. Please, could you help? Many thanks. Sophie

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#287]

**Comment by tuurma** [comment]
puzzled by this one but confirm the problem is there
@JoernT could you possibly help?
looks like when calling subform with https://github.com/eXistSolutions/LGPN-ling/blob/master/editor.xhtml#L324 the `Flux.dispatchEvent.dwr` event is not created at all, compared to other places where I am calling subforms in a similar manner; what is puzzling this stopped functioning seemingly out of the blue; any ideas?

**Comment by JoernT** [comment]
Am 02.11.16 um 13:01 schrieb Magdalena Turska:
> puzzled by this one but confirm the problem is there
> @JoernT <https://github.com/JoernT> could you possibly help?
> looks like when calling subform with
> https://github.com/eXistSolutions/LGPN-ling/blob/master/editor.xhtml#L324 the
> |Flux.dispatchEvent.dwr| event is not created at all, compared to other
> places where I am calling subforms in a similar manner; what is puzzling
> this stopped functioning seemingly out of the blue; any ideas?
Hi Magda,

would be best to look at it together. I'm probably not reachable
tomorrow forenoon but should be online early afternoon.

Joern
