### ISSUE TITLE
suffixes

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#289]
from @hippodamie

Dear Magdalena,

We have finished the lists of the suffixes of the 4 levels in the frame of the Proceedings of our previous conference SAGA.
Could you please put the last suffixes to add to the lists of the Edit window?

Here are the items:
No new S4 item.

— S3 list, add:
ίων (at the end, after ιχ)
ων  (at the end, after ίων )

— S2 list, add.:
(ϝ)εσσ (between (ϝ)εν(τ) and ιππ)
ων  (between (V)νν et ιαν): Current order to change in such a way that we finally have: αιν, (V)νν, ων, ιαν, (V)ν(δ), (V)ν(θ).

— S1 list, please:
1.Change -ον into: (έ)ον,  AND:  (V)τᾱ/ης into: τᾱ/ης
2. Μerge, please: έᾱς/είᾱς and έης/ῆς into: έᾱς/είᾱς/έης/ῆς.

3. Add.:
ην  (between εύς and ήν)
τᾱ/η  (between ς and (V)τᾱ/ης)
τις (between τηρ and τος)
τος  (between τις and τωρ)                   We will have thus: τᾱ/η, τᾱ/ης, τηρ,  τις, τος, τωρ, υς.
ά̄(ϝ)ων  (between ων and ωρ).

The end !
Many, thanks again.
With best wishes,
Sophie

**Comment by tuurma** [comment]
> 1.Change -ον into: (έ)ον, AND: (V)τᾱ/ης into: τᾱ/ης
> 2. Μerge, please: έᾱς/είᾱς and έης/ῆς into: έᾱς/είᾱς/έης/ῆς.

these require updating all existing documents to reflect the change wherever old values were used

**Comment by Hippodamie** [comment]
Dear Magdalena,

Sorry for that: actually, the change to -(έ)ον does not look good at all, what I only understand seeing it on the visualisation as you made the change.
Could you, please rather add έον in the S1-list, just between ε(ι)ᾰ/είη and εύς, and let ον as it was. Many thanks. We need both.

We will anyway have to up-date Structure for each of the 1392 names as soon as you will have implemented the new edition interface. So we will control also suffixes. Many, many thanks for the Suffixes up-dating you already did.

Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

I hope you are well and all your family.
As you know, we are very impatient to be able to edit all the names which are ready for a long time on paper to be edited, and also to revise the 1392 names adding the new informations in the Structure column of the database. It is a huge work for the small team involved this academic year before we get fundings. So we would like to begin the work as soon as possible so that we have time and are not in a hurry, which is not good neither for the work nor for people.

Could you please tell me how many days you need and when exactly it will be ready?

Many thanks in advance.
Have a nice day.
With all best wishes,
Sophie
