### ISSUE TITLE
homonymous roots

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#291]
> @hippodamie 
> In some cases, we have roots perfectly homonymous.
> Example :
> label αγαλλ root αγαλ(λ) can have 2 different meanings, depending of the name. Here, the female Ἀγαλλίς Agallis2, different of Ἄγαλλις1 and of all the other Agall- names has the meaning of ‘dwarf iris’ whereas the other have the meaning ‘exult, be proud’. Actually, I believe (not sure) that it is the same sole root αγαλλ. But I cannot add the flower meaning after ‘exult, be proud’, as a 3rd meaning, since actually we are quite sure that most people who bore this name got it because of the ‘exult’ meaning.
What to do ?
> Would it be possible to add a number 1 or 2 at the root itself as we did for the name itself ? And where to put it? In the label box or in the root box of the sub-window?

**Comment by tuurma** [comment]
I think the approach with creating two separate root entries would be most appropriate.
The way to do it in the subform is to add a number or other modifier to the `label` field, which stores root's identifier 
![screenshot 291](https://cloud.githubusercontent.com/assets/449468/20972719/bc0d80f6-bc8d-11e6-95a6-bb2f13a01461.png)

Afterwards both homonymous roots will be available in the autocomplete field
![screenshot 290](https://cloud.githubusercontent.com/assets/449468/20972755/d569d3ec-bc8d-11e6-8c2e-697a76e3872f.png)

**Comment by Hippodamie** [comment]
Perfect! In the label, you are right, since the root properly will be the same in both cases.
2 Connected questions:

1. Would not it be clearer if we add 1 to αγαλλ vs. αγαλλ2, to see directly that there are homonymous?
2. Would it be  a problem or not if we have thus: a Name Agallis1 AND other names as Agallias, Agallidas etc., all corresponding to Label αγαλλ1 (vs. Agallis2 Label αγαλλ2)?

**Comment by Hippodamie** [comment]
Perfect! In the label, you are right, since the root properly will be the same in both cases.
2 Connected questions:

1. Would not it be clearer if we add 1 to αγαλλ vs. αγαλλ2, to see directly that there are homonymous?
2. Would it be  a problem or not if we have thus: a Name Agallis1 AND other names as Agallias, Agallidas etc., all corresponding to Label αγαλλ1 (vs. Agallis2 Label αγαλλ2)?

Wonderful, Magdalena !

MANY, MANY THANKS for all the work that you have done ! The 2 interfaces look wonderful. All our CONGRATULATIONS !
We are very excited at the idea to test it, tomorrow now !

Thank you for your patience too !
Good night.
Best,
Sophie

**Comment by tuurma** [comment]
I think distinguishing homonym names like you suggested is a sensible practice and I saw you already did enact it. 

A note about adding numbers to roots, though:

I assume that you may not be aware of other root meanings when adding the root and its meaning for the first time. Therefore it would receive an identifier without a number (eg αγαλλ). Second meaning may be added after some time (with a number, eg αγαλλ2), but meanwhile the first root will be already used, potentially on a number of names. Changing the identifier for the first homonymous root (to αγαλλ1) would require update to all names linking to that root so far. 

We could obviously make it an automated procedure, but for the moment we are unfortunately out of time and budget to do so, therefore I would advise a policy where first homonymous root has no number, only the second gets it.

**Comment by tuurma** [comment]
![screenshot 293](https://cloud.githubusercontent.com/assets/449468/21014765/277d947e-bd57-11e6-9343-771f8061fa01.png)

a screenshot illustrating how to treat two homonym names, just for the future :-)

**Comment by Hippodamie** [comment]
OK, Magdalena, thanks for the note. You are right.
Could I ask you, please, to automatically delete the number1 that I just added for all other αγαλλ than our αγαλλ2 ? Ony if it is quite quick for you.

Many thanks again.
Best,
Sophie

P.S.: What is your exact title so that I can quote your name in my application and make know your name everywhere ? Is it enough and exact to speak about you as an IT specialist? I do not think so...

**Comment by Hippodamie** [comment]
Many thanks.
I keep it.

**Comment by tuurma** [comment]
I've changed the names using αγελλ1 back into αγελλ and deleted αγελλ1 root

**Comment by Hippodamie** [comment]
Many thanks !
