### ISSUE TITLE
Visualization Design

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#293]
Hi, Magdalena !

It works perfect, many thanks !
About the visualization in column Structure:
1. Why the unnecessary comma in the parenthesis, for example after YX? Could you, please, delete it?
2. AbbrC does not need to be between its proper parentheses since you will have sometimes N ((AbbrC)) with the double parentheses, which looks bizarre (see Aischis)! Neither Irr would need any parentheses. Just to be add after, for example, XY/YX, in this visualization: (XY/YXIrr).
Have a nice day. Many thanks again for your work.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
One question about AbbrC, since it is a characteristic of a compound, I thought we need to signal on which (root1 or root2) it belongs, which is why I placed it next to headedness information, not at the end. What do you think?

Assuming that root1 has both X and AbbrC checked and root2 Y (and possibly also AbbrC at the same time?), how would you like the summary to look like?
