### ISSUE TITLE
Entry form: Sublemma labels

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#335]
/estimate 8h

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/33953966-2adace26-e037-11e7-8328-f764cf20e756.png)

TEI representation as 

```xml
<gramGrp type='classification'>
  ...
  <gram type="sublemma" ana="polysemic">1</gram>
</gramGrp>
```

**Comment by Hippodamie** [comment]
Polysemic is unnecessary. We just need the Sublemma box as you planned it.
The sublemma labels are there to help us to range the names by different series in the book. To rebuild the etymological family when different roots are linked as for:
ἀγάλλω v. « glorifier, exalter », part. aor. actif ἀγήλας, adj.  -αγαλτός. Ἀγαλλ(ο)- XYAbr. ; -αγᾱ/ήλας. B9. -αγάλτη YX. <2> ἀγαλλόμενος part. pr. hom.  « qui exulte, fier ». <3> ἀγαλλίασις f. « joie » (LXX+). <4> ἄγαλμα n. « délice, gloire, statue ». →? ἀγαλλίς f. (H. Dém.), var. ἀν-αγαλλίς  « iris nain » (Dsc.). B595.

The corresponding personal names will have the numbers corresponding above to differents lexis. And in the book all names will be listed under this common head entry.
We will have thus under it the following list:
      Agallias
<2>Agallomenos
<3>Agalliasis,
<4> Agalma
→? Agallis
The numbers are a way to signal the names belong all to the same etymological family but are not exactly on the same level (which means they share the smaller form of the root, since many of them derive from it). The most often the names coming first (number 1 actually) will have their form the most close to the  smaller form of the root – here agal(l).
→? means : we are not sure it belongs to this family.

Best,
Sophie
