### ISSUE TITLE
Entry form: Adjust labels for the entry form

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#338]
/estimate 2h

**Comment by tuurma** [comment]
@hippodamie, please remind us if any form labels still require adjustments

**Comment by Hippodamie** [comment]
Dear Magdalena,

Here are the only changes necessary:

Semantics of the name and Evidence to be changed into: Lexical connections

Just below:
Souces, into: Lexical or lexicographic ancient sources

Lexicographic references, into: References in modern Lexicology and Linguistics


Below:
Onomastics and linguistic bibliography into: Onomastics 

just below:

Parallels in Onomastics
Be careful, NEW (but already asked in my first long scheme): we would like to have there, for the Onomastics parallels, a quotation box, just the same (with ref, author details) as for the above new ‘Lexical or lexicographic sources’. Able to be repeated, since we have sometimes 3 different sources to quote

then:

Modern references



with many thanks and all best wishes,
Sophie

**Comment by tuurma** [comment]
@Hippodamie could you please check the last section? Do you need more similar groups below Onomastics?

![image](https://user-images.githubusercontent.com/449468/34053916-eccecfe0-e1c8-11e7-931b-698038f2688e.png)

**Comment by Hippodamie** [comment]
Yes, we need a + also under Onomastics quotation (until 3 possible).
And of course Modern references under Onomastics too.
Thanks.
Best,
Sophie

**Comment by tuurma** [comment]
Please note that Lexical...sources, References... and Onomastics are all repeatable sections (via + button to the right of the section name).

Shall I add a new section with identical structure for Modern references?

**Comment by tuurma** [comment]
Like this? Red circles mark button to add new records

![image](https://user-images.githubusercontent.com/449468/34054555-d42848ec-e1cb-11e7-9008-e754ca18a749.png)

**Comment by Hippodamie** [comment]
Totally perfect : how can you do so quick ???

**Comment by tuurma** [comment]
This is just a mockup, but even adding this section is not too much work, as its structure is identical to others. Last question: don't you think it makes sense not to have the 4 subsections with empty entries by default but rather add them as you need via + button? This would be the view at the start:

![image](https://user-images.githubusercontent.com/449468/34054769-a8392d4a-e1cc-11e7-8338-1f543a7c241f.png)

and after clicking one of the buttons (Onomastics)

![image](https://user-images.githubusercontent.com/449468/34054807-c74193ee-e1cc-11e7-8197-daf4d39d944d.png)

**Comment by Hippodamie** [comment]
Magdalena, sorry if you already wrote me about it or if I did not understand well: are you currently dealing also with the new distribution of both types of sources and references (Lexical and Onomastics) in such a way that each (high and low) hypothesis will have its own, as I had asked?

Thanks,
Sophie

**Comment by tuurma** [comment]
I am afraid not. I very vaguely remember we have discussed it at a time, but there's no trace of it in my notes, nor was it included in the estimate. How would you imagine it?

**Comment by Hippodamie** [comment]
I think that in view of my just previous email, since the aim is to have for each hypothesis its own Lexis and Onomastics (4 subsections), it would be better when we start just to see the titles, so that the edition page is not too long, for us to be able to entirely see it on our screens, if possible !
But in this case, could you please make some hierarchy visible, with the main titles bigger thant the subtitles ?

But I think a title is missing: Onomastics is a main title. Its subtitles are : Other sources (I changed since previously) ; Modern references.

Please delete « ancient » if it is not time consuming before sources.

**Comment by tuurma** [comment]
I see, there is something about repeating references for each hypothesis briefly at the end of the Google Doc https://docs.google.com/document/d/1hnYmmMbCB6JtX1Ps1bnbNW742y5Ad43UKSzF0y5jjhk/edit. I must have completely missed it.

> 11. We definitely need that every hypothesis has its corresponding Lexis and Onomastics boxes and columns. To put everything in order. So that 8. above would have to be repeated as many times as they are different hypotheses.

Shall I then move all references into hypotheses? How should the existing multi-hypotheses entries be treated? Move existing references into high hypothesis or copy into both?

**Comment by Hippodamie** [comment]
The aim is that the references corresponding to each hypothesis is not grouped all together but that we could open all 4 subsections under each hypothesis (they are the most often not more than 2) and not only at the end of both, as now.
I am sure I have asked for.
It was an important point for us, for a long time.

See attachment, number 11 ( a Word copy here of the Googledocs document), the last one.

**Comment by Hippodamie** [comment]
OK, nice, you are quicker than I !!!
I think, but please, could you confirm it, that if you copy them in both, it will be quicker for us, since, we just will have to delete what is to delete by the button? In the other case, we will have to write again.
I ask for your advice.

**Comment by tuurma** [comment]
I think if I copy it will be indeed quicker for you to just go through them and delete superfluous entries. I will extract another issue then for this task and close this one.

**Comment by tuurma** [comment]
Last questions on labelling though, could you confirm the structure and labels for all reference entries?

![image](https://user-images.githubusercontent.com/449468/34056077-f6e7e33c-e1d1-11e7-864a-d075d9f921c7.png)

**Comment by Hippodamie** [comment]
OK. Many thanks.

**Comment by Hippodamie** [comment]
Please, substitute « significant »  for « ancient » before Sources. Thus we would better have: « Lexical or lexicographic significant sources ».

And under Onomastics:

not Other Sources, but better: Linked sources. 

I am back at 9, if you need.

**Comment by tuurma** [comment]
Thank you very much for your help and good night!

![image](https://user-images.githubusercontent.com/449468/34056429-3f23fd92-e1d3-11e7-86cb-909ebfcb277c.png)

**Comment by Hippodamie** [comment]
Great ! Many, many thanks, Magdalena.
Good work and good night,
with all best wishes,
Sophie
