### ISSUE TITLE
Entry form: Fix problems for names with multiple-hypotheses

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#339]
improve the layout and css based on what @plutonik-a has done for LGPN

/estimate 8h

**Comment by tuurma** [comment]
@plutonik-a there are 3 main tasks here

* [ ] 1. adjust the layout and styling similarly as you have done for LGPN
* [ ] 2. make sure that newly added repeat sections are correctly styled
* [ ] 3. hide superfluous autocomplete-related fields

Example of 2

![image](https://user-images.githubusercontent.com/449468/34041405-44cabd3e-e198-11e7-853c-34e395465f29.png)

Example of 3 

![image](https://user-images.githubusercontent.com/449468/34041490-85a8ff78-e198-11e7-8117-11eff3f8d7ea.png)

![image](https://user-images.githubusercontent.com/449468/34041479-7900c4cc-e198-11e7-969d-96b266248c33.png)

**Comment by tuurma** [comment]
@plutonik-a compacting the form, if possible would be great too. When you're back let us know your availability please. With any questions for the form please @-mention @hippodamie as well.

**Comment by Hippodamie** [comment]
Hello, Magdalena

looking at that, I remember something difficult for us to find back in the autocomplete lists when we are looking for α (alpha) alone. I almost never find it in the list, I do not know where it is listed!

**Comment by plutonik-a** [comment]
Dependent on #360

**Comment by plutonik-a** [comment]
Status Mon 8<sup>th</sup>:

![fireshot capture 005 - lgpn - http___localhost_8080_exist_apps_lgpn-ling_editor xhtml](https://user-images.githubusercontent.com/1157669/34679377-0a7a67b8-f496-11e7-8845-59f5dac54704.png)

**Comment by Hippodamie** [comment]
It looks perfect ! Many thanks,
best,
Sophie

**Comment by plutonik-a** [comment]
I've made changes in the form layout:
* space-saving labels above inputs
* longer label content is possible now

Status today after latest layout changes:

![fireshot capture 006 - lgpn - http___localhost_8080_exist_apps_lgpn-ling_editor xhtml](https://user-images.githubusercontent.com/1157669/34789675-7f7a765c-f63f-11e7-839a-4a1e5f15dcc2.png)

**Comment by Hippodamie** [comment]
Good job : many thanks !
Just a small remarks

Irr is written twice (Segmentation) and would be bettre on the same line as Structuration and Semantics of the Complex names, just after.

with all best wishes,
Sophie

**Comment by plutonik-a** [comment]
Hi @Hippodamie,
> Irr is written twice  

I changed the layout like that: 
* there is **always** a text label as a over each input (instead of the obsolete icons) to show users the context within the section
  <img width="367" alt="bildschirmfoto 2018-01-11 um 12 22 49" src="https://user-images.githubusercontent.com/1157669/34823306-30a2b46e-f6ca-11e7-8c71-2378971352fb.png">

* checkboxes have an additional text next to the right, that are indicating each available option
  <img width="105" alt="bildschirmfoto 2018-01-11 um 12 22 36" src="https://user-images.githubusercontent.com/1157669/34823327-44aff08e-f6ca-11e7-8ea6-e5a9bd46f86b.png">



So please consider all the above labels as a suggestion or temporary placeholder for the UI.
In the case "Irr", I had no other information, so I used the option as a label.  
I can just guess, what the correct content might be suitable for the inputs.

But it would be really great, if you could help me with providing all missing or alternative label texts as they suit your Interface best.

> and would be bettre on the same line as Structuration and Semantics of the Complex names, just after  

The layout has a 2-columns grid, so only two inputs will be placed in each line on wide screens (on smaller screens it will switch to a 1-column grid). 
I would like to stick to this structure, because otherwise we have an irregular grid system that will cause a messy impression in the end.  
I would like to finish the form first and in the end you are going to decide, where it is particularly necessary to deviate from the 2-column grid. Is that ok?

**Comment by Hippodamie** [comment]
Hi, Alexandra,

very well.

1. Could you, please, below switch H-Variant and LGPN, so that we have both Latin forms to write on the same side, at right? Thus, the LGPN under the Greek, at left?
2. Could you intitle all: not General but rather Head-name


3. Would it be possible for Name variants to have the ? not only after the dialect but also just after the form of the variant itself ?
4. Could you please, re-intitle Name variants now : Head-name's dialectal and gender variants
5. New title for Segmentation and Root interpretation : Segmentation and Semantics
Then:


6. Irr is for the so-called ‘Irrational combinations’. Could you please actually include this Irr. label in the labels list of ‘Structuration of Complex names’, at the end of the list? You could rather write ‘Irrational’ in full.
7. No more Preroot but Prefix. But keep Preconstituent1.

I am ready to have what follows on the Segmentation part ! 

Many thanks,
with all best wishes,
Sophie

**Comment by plutonik-a** [comment]
Hi @Hippodamie,
Please have a look, if I understood you correctly:

**1.** Done
  <img width="894" alt="bildschirmfoto 2018-01-11 um 14 06 04" src="https://user-images.githubusercontent.com/1157669/34826898-a7ed5214-f6d8-11e7-846d-8e23fa2e222a.png">

**2.** 
  > not General but rather Head-name

I understand, that you want to 
* change the wording of headline "General" to "..." (Head-name, what is that?) and that you want 
* all sections to be headlined like the "General" headline, meaning, a headline above the gray form box, am I right? 

**3.** Done, like this?
  <img width="994" alt="bildschirmfoto 2018-01-11 um 14 26 09" src="https://user-images.githubusercontent.com/1157669/34827745-7b4f1ba4-f6db-11e7-98e7-a97ba674f97a.png">

**4.** Rename
> Head-name's dialectal and gender variants

Can you paste in the exact wording, please? And also where to exactly place it, because I don't quite understand your request.

**5.** Done
<img width="1033" alt="bildschirmfoto 2018-01-11 um 14 31 10" src="https://user-images.githubusercontent.com/1157669/34827949-2359b9a8-f6dc-11e7-8477-340791827773.png">

**6.** Done, like this, both in a checkbox and as a select option?
  
<img width="975" alt="bildschirmfoto 2018-01-11 um 14 35 03" src="https://user-images.githubusercontent.com/1157669/34828124-c5039abc-f6dc-11e7-8834-ec26b99e56d1.png">

**7.** I will think of a slightly better visual grouping and this is what I understand: 
(Labels with"TBD" need content btw...) 
<img width="1086" alt="bildschirmfoto 2018-01-11 um 15 04 37" src="https://user-images.githubusercontent.com/1157669/34829399-ea652c18-f6e0-11e7-8bf3-845d544c3d20.png">

**Comment by Hippodamie** [comment]
Hi, Alexandra,

What does mean TBD ?

**Comment by plutonik-a** [comment]
@Hippodamie 
> What does mean TBD ?

-> "To be done"
Just a placeholder to indicate missing content here.

**Comment by Hippodamie** [comment]
Hi, Alexandra,

to come back to your ‘General’.

You could also title : Name in context.
The title title would work, not only for the first grey box, but also for Dialects and then Variants = until Variants included. For all, thus, before Segmentation…

Good evening,
best,
Sophie

**Comment by plutonik-a** [comment]
@Hippodamie 

**2. (Renaming General -> Name in context) Done**
<img width="1030" alt="bildschirmfoto 2018-01-11 um 17 21 49" src="https://user-images.githubusercontent.com/1157669/34835024-f2e2144c-f6f3-11e7-9d4c-2f7b9a9d04a2.png">


**3. (Name Variants) That's confusing:**
>  put the ? not after the form but before it

Do you mean 
* moving checkbox `Form: uncertain` ( + label `?`) entirely **before** the form input 
* and leaving the `Dialect: uncertain` checkbox ( + label `?`) after the text input?

**4. Providing headline contents**
I think you might have misunderstood me here. I need the wording for labelling the inputs and checkboxes correctly, because you know best, what is supposed to be there. I can just guess...
So wherever you discover a "TBD" in the app, I would appreciate getting a correct label text from you.

**5. Done, removed checkbox "irrational"** 

<img width="968" alt="bildschirmfoto 2018-01-11 um 17 05 26" src="https://user-images.githubusercontent.com/1157669/34834196-a9419418-f6f1-11e7-9a18-12344036f8e7.png">

**7.**  
    **a)** Add a question mark after the input "linked compound" -> Done
Unfortunately, this rather small feature request will take some time to get ready, because of the current framework working in the background. Could we prioritize this to "low" for now?


**b)** rename placeholder text "linked compound" to "‘exempli gratia’ linked compound" -> Done
  
<img width="483" alt="bildschirmfoto 2018-01-11 um 17 27 04" src="https://user-images.githubusercontent.com/1157669/34835494-46eaa8dc-f6f5-11e7-9559-0e7015c0cff4.png">

**Comment by Hippodamie** [comment]
Hi, Alexandra….
please, look below:
> Le 11 janv. 2018 à 17:32, Alexandra von Criegern <notifications@github.com> a écrit :
> 
> @Hippodamie <https://github.com/hippodamie>
> 2. (Renaming General -> Name in context) Done
> 
Well done !
>  <https://user-images.githubusercontent.com/1157669/34835024-f2e2144c-f6f3-11e7-9d4c-2f7b9a9d04a2.png>
> 3. (Name Variants) That's confusing:
> 
> put the ? not after the form but before it
> 
> Do you mean
> 
> moving checkbox Form: uncertain ( + label ?) entirely before the form input
> and leaving the Dialect: uncertain checkbox ( + label ?) after the text input?


3. I would like 2 ??. 
To keep: the Form: Uncertain, with its ?. AND to have before the Form box, another ?. This ? would mean: ‘Uncertainly linked form’. 

Currently ‘Uncertain’ means the reading of the form (palaeography, on the stone) is uncertain. The new ? would mean something else: we are not quite sure the variant is really a variant of the main Name.


> 4. Providing headline contents
> I think you might have misunderstood me here. I need the wording for labelling the inputs and checkboxes correctly, because you know best, what is supposed to be there. I can just guess...
> So wherever you discover a "TBD" in the app, I would appreciate getting a correct label text from you.
> 
> 
4. OK.
> 5. Done, removed checkbox "irrational"
> 
>  <https://user-images.githubusercontent.com/1157669/34834196-a9419418-f6f1-11e7-9a18-12344036f8e7.png>
> 7.
> a) Add a question mark after the input "linked compound" -> Done
> Unfortunately, this rather small feature request will take some time to get ready, because of the current framework working in the background. Could we prioritize this to "low" for now?
> 
> b) rename placeholder text "linked compound" to "‘exempli gratia’ linked compound" -> Done
> 
> 
7.b. I do not know if you are also working on the visualization, but could you please notice that on the Visual, we do not nee to read the full ‘exempli gratia’ but only the abbreviation : e. g.

Many, many thanks for your job !
Best,
Sophie

**Comment by plutonik-a** [comment]
Hi @Hippodamie,
my latest fix for your requests above:

**3. Uncertain Form**
Considering the 2-column layout, I found this was the best solution. I tried also a 3 -column layout, but it turned out to look messy as I expected. 

<img width="990" alt="bildschirmfoto 2018-01-11 um 19 16 34" src="https://user-images.githubusercontent.com/1157669/34840082-31dfd4ee-f704-11e7-873d-f4572605e73d.png">

**7b. Change placeholder text**
Yes, I definitely also work on the visualization of the app.  
Funny, but even with having had my bac in Latin, I didn't realize that "e.g." is the abbreviation of *exempli gratia*, good to know!

<img width="486" alt="bildschirmfoto 2018-01-11 um 19 27 23" src="https://user-images.githubusercontent.com/1157669/34840524-7c0ca8d4-f705-11e7-8497-4179ede9580d.png">

I hope, everything has been done here so far and finally turned out the way you expected.

**Comment by Hippodamie** [comment]
Hi, Alexandra

3. is almost done, but the reverse for the texts : at left linking of the form is uncertain ; at right Reading of the form is uncertain.
> Le 11 janv. 2018 à 19:29, Alexandra von Criegern <notifications@github.com> a écrit :
> 
> Hi @Hippodamie <https://github.com/hippodamie>,
> my latest fix for your requests above:
> 
> 3. Uncertain Form
> Considering the 2-column layout, I found this was the best solution. I tried also a 3 -column layout, but it turned out to look messy as I expected.
> 
>  <https://user-images.githubusercontent.com/1157669/34840082-31dfd4ee-f704-11e7-873d-f4572605e73d.png>
> 7b. Change placeholder text
> Yes, I definitely also work on the visualization of the app.
> Funny, but even with having had my bac in Latin, I didn't realize that "e.g." is the abbreviation of exempli gratia, good to know!
> 
> 
wonderful, if I can learn you something (you learnt me TBD!) !
So, e.g. also in the visualization !
Good night,
best,
Sophie

**Comment by plutonik-a** [comment]
Hi @Hippodamie,

I swapped the order of the inputs now like this:
<img width="755" alt="bildschirmfoto 2018-01-12 um 11 45 17" src="https://user-images.githubusercontent.com/1157669/34871510-34de6f86-f78e-11e7-8011-afed3255ceb6.png">

**Comment by Hippodamie** [comment]
Hi, Alexandra,

Wonderful ! Many thanks.

Please, excuse me : I juste remember we need another ? which could have exactly taken the place of teh old Irr box yoy taook off yesterday.
I am so sorry for that.
Look below:


The idea is to be able to add a ? after the Structuration and Semantics of the Complex names labels: for example after > YX, after Irrational etc. To be able to mark the uncertainty.


Best and many thanks,
Sophie

**Comment by plutonik-a** [comment]
@Hippodamie 
Now you confused me. I think painting you request directly in the screenshot makes it clearer for me to understand. Can you make some annotations in this screenshot?  

This was the before state:
<img width="975" alt="bildschirmfoto 2018-01-11 um 14 35 03" src="https://user-images.githubusercontent.com/1157669/34828124-c5039abc-f6dc-11e7-8834-ec26b99e56d1.png">

And this was after my changes, which I posted in an earlier comment:
<img width="968" alt="bildschirmfoto 2018-01-11 um 17 05 26" src="https://user-images.githubusercontent.com/1157669/34834196-a9419418-f6f1-11e7-9a18-12344036f8e7.png">

**Comment by Hippodamie** [comment]
Sorry, Alexandra !




Just keep the square box, but give it a new name and aim.
Call it: Structuration: uncertain.
and put the ? juste aside the box instead of Irr.

It is aimed to let know that the Structuration … of complex names label is given, but as uncertain. So it is logically connected to the Structuration…. list.

Hope you understand better…
Many thanks.
Best,
S.

**Comment by plutonik-a** [comment]
@Hippodamie 
Done.

<img width="978" alt="bildschirmfoto 2018-01-12 um 13 49 17" src="https://user-images.githubusercontent.com/1157669/34875898-709226e2-f79f-11e7-82bf-ee28a7a7674f.png">

Another thing: I reordered the name variant section and also dropped the dividing lines. Does this make more sense now?
<img width="988" alt="bildschirmfoto 2018-01-12 um 13 48 13" src="https://user-images.githubusercontent.com/1157669/34875922-95f0e82e-f79f-11e7-86e0-35d6d8095daf.png">

**Comment by Hippodamie** [comment]
Perfect : many, many thanks, Alexandra,
Sophie

**Comment by plutonik-a** [comment]
@Hippodamie 
I'm thinking of grouping these inputs in a more effective way. Should I group everything with number 1 together and after that group 2?

In a table of rows, that would be following grouping:

column 1 | column 2
------------ | -------------
Constituent 1 | Root 1
Function 1
Headedness classification 1 | Abbreviation marker 1
Class marker 1 | Linked Compound 1
Constituent 2 | Root 2
Function 2
Headedness classification 2 | Abbreviation marker 2
Class marker 2 | Linked Compound 2

Right now, it looks like this:
![fireshot capture 009 - lgpn - http___localhost_8080_exist_apps_lgpn-ling_editor xhtml](https://user-images.githubusercontent.com/1157669/34883924-6f67132e-f7bb-11e7-9bff-ef013f05ca0a.png)

**Comment by Hippodamie** [comment]
Hi, Alexandra,

Could you, please, give a screen shot of the whole you did, from the top to the bottom : I would like to have a look and especially to all the ?. To be sure it is not confusing.
(I mean that it is sometimes better to put the ? before the uncertain item rather than just after, since when yoy have a line with several informations, if you put the ? at the end, one can understand that the whole line is uncertain.

Have a good week-end,
many thanks for all your work,
with all best wishes,
Sophie

**Comment by plutonik-a** [comment]
@Hippodamie 
**ad 1. Move "Structuration and Semantics of Complex Names"**
Do you want to move this whole group 
<img width="972" alt="bildschirmfoto 2018-01-12 um 18 39 57" src="https://user-images.githubusercontent.com/1157669/34887881-56fa1f5e-f7c8-11e7-94de-79c91fadd33b.png">

down to the segmentation below input fields Suffix 1- 4?

**ad 2.**
I will discuss that point with Magda @tuurma and see, if we can do this within this iteration.

**Comment by plutonik-a** [comment]
@Hippodamie 
> Could you, please, give a screen shot of the whole you did, from the top to the bottom

Sure, but please keep in mind, that I'm not ready with fixing the layout. I'm currently fixing the section "References in Modern Lexicology and Linguistics", "Onomastics" and the Save/Delete buttons at the end of the form.

Here you go:
![fireshot capture 012 - lgpn - http___localhost_8080_exist_apps_lgpn-ling_editor xhtml](https://user-images.githubusercontent.com/1157669/34888102-2af43b14-f7c9-11e7-8a96-28c61c31b7d3.png)

**Comment by Hippodamie** [comment]
Not ‘Certainty’, of course,
but both, you are right ‘Structuration and Semantics of the Complex names’ (maybe just call it Complex Structuration and Semantics) and the ‘Structuration: uncertain’ 
Best, and thank you for the full screenshot !
Have a good w.e.,
, Sophie

**Comment by plutonik-a** [comment]
@Hippodamie 
> Not ‘Certainty’, of course,
but both, you are right ‘Structuration and Semantics of the Complex names’ (maybe just call it Complex Structuration and Semantics) and the ‘Structuration: uncertain’

What are you referring to in your last post?

I changed label `Structuration and Semantics of the Complex names` to -> `Complex Structuration and Semantics`

This is the screenshot of today's fixes (apart from the to be discussed point 2 you asked for in earlier post https://github.com/eXistSolutions/LGPN-ling/issues/339#issuecomment-357298798).
This means the Interface's **layout** should be ready by now, content like label/headlines can still be changed, of course:

![fireshot capture 014 - lgpn - http___localhost_8080_exist_apps_lgpn-ling_editor xhtml](https://user-images.githubusercontent.com/1157669/34890666-1c98b248-f7d3-11e7-91d0-69714fcd8393.png)

**Comment by Hippodamie** [comment]
Hi, Alexandra,

1. For Significant relative name, please in the relation box, add : e. g. before son, etc. Thanks !

2. Dialects : yes, we need the uncertain marker.

3. Could you, please, put the Structuration uncertain at right, under Complex structuration and Semantics ? It would be more convenient and logical.

4. . A problem: for the 3 linked compounds. It does not work with the Class marker * separately. And ‘Class marker’ is not right:     * = ‘unattested’. Actually we will need to be able to write:
< e.g. Φιλόμενος
or
 < e.g. *Φιλόμενος
Maybe could we put the asterisk  in the box (directly before the Greek name) and delete the so-called ‘class marker’? What do you think? Or <, e.g. and * would have to be out of the LInked compound box and have each its own box?
[Note that I just add now the < mark, which would be clearer].
So, if we look at  < e.g. *Φιλόμενος, it means maximum 4 items : 2 obligatory marks (< and e.g.), then the Greek name and, finally, the optional mark (*)


5. Perfect for the rest of the box. Congratulations !

6a. A question: rather than a mere quotation, under References in Modern Lexicology and LInguistics and under Modern References in Onomastics, the most often we use parentheses to put comments explaining briefly the content of the Reference, that we would like to see in Visualization just after the Details : as for example :
Cf. aussi HPN56 ( Ἀνθέας, Ἀνθεύς etc.) = Reference + no author + (comment)
If you consider our parentheses could stay in Details (with the page number), so we do not need quotation for both those modern references.

6b. Note that we have two sorts of modern references : some come directly (when they deal with the name which is our subject), but some others need a Cf. mark before (Latin confer !): it means ‘see also’ (for linked informations, not as important as the other without Cf.)
Should that Cf. appear separately ?



MANY thanks again,
Have a good week-end,
Sophie

**Comment by Hippodamie** [comment]
HI, Magdalena : Version A is the best, I think (it is the closest of the current version, which is good).

1. QUESTION: does the proposed new order "meanings, functions and then headedness » in Edition mean it will have to be re-ordered in Visualization too? 

2. What is « add morphem » ? Do you mean « add root » ? Suffixes are morphems.

3. Do you remember, about Suff1 I have asked to change the name into Flect1 and I sent you on Git HUb a new soft list of Flect1 Nominative + genitive to substitute for the current S1 list? And could you please in the Visualization make as I asked (italics for Flect1, and smaller size for the Genitive form under the nominative form?)

Have a good week-end (or could you please answer to my question 1.?: I come back late in the afternoon),
with all best wishes and thanks,
Sophie

**Comment by tuurma** [comment]
@hippodamie The order in the firm doesn't affect visualization, so we can
rearrange the form as is most effactive for editors

I will apply other changes you asked for regarding Flect etc but will
comment on these subjects in their own threads.

Many thanks for quick reply before your holiday!

sob., 14.04.2018, 10:47 użytkownik Hippodamie <notifications@github.com>
napisał:

**Comment by tuurma** [comment]
And yes, add morphem should be renamed add root, thanks!

sob., 14.04.2018, 11:37 użytkownik Magdalena Turska <tuurma@gmail.com>
napisał:

**Comment by tuurma** [comment]
Currently preroot/root1/root2 sections follow the same pattern

![image](https://user-images.githubusercontent.com/449468/38811607-451a2e08-418a-11e8-844d-317d1cdee900.png)

**Comment by plutonik-a** [comment]
Layout fixed with https://github.com/eXistSolutions/LGPN-ling/commit/f17608701bb13fd3b540a6bee9aff72965f38b86 and https://github.com/eXistSolutions/LGPN-ling/commit/696e7008433d4d9b7998e223e211ab20efe052a7

<img width="999" alt="bildschirmfoto 2018-04-17 um 13 11 46" src="https://user-images.githubusercontent.com/1157669/38866351-eddd342a-4240-11e8-9b88-b1c50fb6eb35.png">
