### ISSUE TITLE
Entry form: Linked name for abbreviated compounds

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#340]
/estimate 4h

**Comment by tuurma** [comment]
Dear @hippodamie could you please remind me what this one was about? I must have mislaid my notes.

**Comment by tuurma** [comment]
> We would need a supplementary box under AbbrC for both Roots to put in it another linked Greek name [the Compound of which it could be the abbreviated form: we should have: Cf. (*)Greek compound name?]. 

>We would need sometimes to be able to put an * just before the initial letter of the Greek Compound name. If we search for these forms, we will need to have them searchable with *Greekname (no space between).

**Comment by tuurma** [comment]
@hippodamie please confirm if this was the intention

![image](https://user-images.githubusercontent.com/449468/33962105-ac4a1a5c-e050-11e7-87cb-73d8e9214952.png)

**Comment by tuurma** [comment]
for TEI we could maybe abuse m/@corresp slightly to accommodate this request without major reworking of the TEI structure

**Comment by tuurma** [comment]
I have one concern, that maybe this is a characteristic of the root itself and not of it's instantiation in a segmented name (so a root in context, so to say). If the former (and the linked name would be the same for all occurrences of the particular root, regardless of the name it appears in), I'd say the 'linked name' field belongs in the morpheme subform.

**Comment by Hippodamie** [comment]
Magdalena,

I have to think about it again.
Back tomorrow for this special point.
Many thanks for your remark and all
Good night,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Abbr. means that names looking for most of them like simple names (1 Root) have to be considered as abbreviation as compounds (mainly double) names.

For example, the simple Anaxias has been labelled XAbbr: it means that it is the abbreviation of a name like Anaxi-laos. We have put the label Abbr with the Root1, the only root visible in the simple name made of the abbreviation of the double Anaxi-laos. We would like to be able to add for this name: XAbbr. e.g. (of) Anaxilaos.

For Ari-mm-as, it is a little different, since it is not exactly a simple name but it is a short form of a double name we supposed to be Ari-menes. It would have to be labelled YXAbbr, because the 2 Roots are visible, but one of them has just kept in the name its first letter (sometimes geminated) which makes it quite ambiguous to identify. We would like to be able to add for this name : YXAbbr e.g. (of) Arimenes. The linked compound will be put

If the name we suppose to be the compound on which has been made the abbreviated form is not attested as a compound but could be at least postulated (as grammatically correct), we would like to put an asterisk before, like: YXAbbr e.g. (of) *Arimenes. 

So it should be called: linked compound.

Now, I answer exactly to your question :
no, it is not linked to the root but to its different instantiations, more exactly to the form of the constituant; with a constituant Agi- of a Root ag- we are quite sure that the name Agias is an Abbr of a compound of Agi-laos type, with the first element having the syntaxic function of verb and the second element of its complement.
It is also possible (work hypothesis) that the peculiar suffix of a peculiar name gives an evidence of the second element which has been abbreviated or shortened: for example, and Agath-ôn could be a short form of Agathônax (constituants Agath- + ônax).

Do you understand better what I mean ?

Best,
Sophie

**Comment by tuurma** [comment]
Thank you for this fascinating explanation! It's quite a detective's work you need to do sometimes :-)
I will stick to the original plan then and try to use the @corresp to store the value of the linked compound.
