### ISSUE TITLE
Wonderful ! The bold types for Suffix 1, Greek name and R1, R2 !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#35]
Many thanks, Magdalena !
Sophie

**Comment by tuurma** [comment]
Thanks Sophie, you can still comment on an issue that has been closed, so this 'thank you' note belongs to the issue #28 Otherwise we arrive with the comments scattered among many threads which will lead to confusion. Moreover if I close an issue and it's not to your satisfaction, you can reopen like here (just a sample comment showing where the Reopen button is)
![screenshot 123](https://cloud.githubusercontent.com/assets/449468/12642521/3da62898-c5ae-11e5-93a3-3bc60a6579a8.png)

though sometimes if an issue only persists in a specific circumstances it is more helpful to start a new issue, like you just did with the case of bold in multiple segmentation cases. Thanks for your help and understanding in this, I think we are getting on with it very well indeed!
