### ISSUE TITLE
Entry form: hide 'quote' box for modern references

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#356]

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/34152275-52599da8-e4ae-11e7-8b37-a166dd56a076.png)

**Comment by Hippodamie** [comment]
Wonderful, dear Magdalena !
I send you another email.
MANY THANKS again !
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

If the quote box could disappear, it would be a lot better, since the page is so long to look at, with the risk to get lost !
I disappear, but will be at work tomorrow morning.
with all thanks and best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

A last question for today : when will we get the visualization?
Best,
Sophie

**Comment by tuurma** [comment]
I have already adjusted the visualization minimally, in order to make it work at all with the new structure. Any substantial work will have to wait until New Year though, as I have to move on to LGPN itself now.

**Comment by tuurma** [comment]
Please, any visualization table requests put into the #357 issue. Sketching the structure there in the meantime will be helpful for when I get back to work on it.

**Comment by Hippodamie** [comment]
Dear Magdalena,

The results of your work are wonderful : thank you very much for all. We are very happy with the renoved app !!!

A question: are we sure that what we edit before visualization is OK is secure, even if we do not see it ? Since we will delete many entries as soon as we have put those names as variants. How can we be sure our variants have been really edited? I used to take copies of our pages, but here the variants will not be visible on the screen ! 

I wish you good work for LGPN.

When will you have vacations? So that Gerard and I know we do not have to disturb you if there is any bug. Because, I know he especially will work during his own vacations. I will be myslf without any computer from the 26 to the 31.

with all best wishes,
Sophie
