### ISSUE TITLE
Visualization: adjust to changed structure

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#357]

**Comment by plutonik-a** [comment]
@magda Please elaborate what has to be done here and how to test and reproduce the steps to test if everything is completed or not.

**Comment by tuurma** [comment]
@hippodamie

Please Sophie, could you have a look at the Visualization table and let us know if any work still remains to be done apart from Suff1/Flex1 column which obviously will be completely changed?

![image](https://user-images.githubusercontent.com/449468/39352947-8e1e710c-4a06-11e8-9b88-b1d901fc6ff2.png)

**Comment by Hippodamie** [comment]
Hi, Magdlena,
do you mean looking at your screenshot or in general?

Looking only at your screenshot, we would like to see son of instead of son.

In general, you remember we discussed about the Translit. and Greek columns to try to avoid repetition when multiple hypotheses names, and to range the variants fater in this case. I am not sure that we have finished this discussion.

I am again available around 2.30 p.m.
Thanks for all,
Best,
Sophie

**Comment by plutonik-a** [comment]
Hi @Hippodamie , 
could you please name the exact place, where I can find the label "son" in the table that Magda pasted in as a screenshot above? 
I would like to add the requested "of", but am not able to find the respective column/place there.

For your mentioned "Translit discussion", could you please refer to the Github issue, if there is already one existing? Otherwise I would like to create a new one, so we are able to keep the overview about open requests and tasks.

//cc @tuurma

**Comment by tuurma** [comment]
> (from #421) Discussion on Visualization design (...)
>The only thing for which I forgot to ask was the following (...):
>We would like not to see the second Ἄλκανδρος in bold. We rather would like it in grey just like the grey (Latin translit). Alkandros.

![image](https://user-images.githubusercontent.com/449468/39425155-6a5fe18a-4c7a-11e8-8869-14407f0fab42.png)

>You just have to write « of » after « son » and the same for the other relations of the same list. Do you understand what I mean?

![image](https://user-images.githubusercontent.com/449468/39425208-a4e5917e-4c7a-11e8-902b-db0912eeb26f.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

1. Look at this visual:


Could you, please, put Euboulos on the same line as « of » ? AND transfer all in the (following) case/box of the Greek form, since we wrote the son’s name in Greek too? As you perhaps meant yourself (below) (?)

2. For Alkandros: for sure, we do not need the repetition of the dialectal informations in the second line: once is enough ! So could you please take it off? 

More difficult to decide: Do you think we could take off the Greek form of the second line too? I wonder in fact if we could have the 3 first cases/boxes empty in the second line, and then the segmentation, with finally variant Ἀλκάνδρη coming third line ? Or we keep in the second line the sole Latin form of the name.

What do you think, for sake of clarity? 

Best, thanks for help !
Sophie

**Comment by Hippodamie** [comment]
Do you think we could even delete Alkandros and the dialects list in grey, of the low hypothesis? = nothing before the low hypothesis segmentation. Thus, we would have only in grey the variant line.

What do you think (for the sake of clarity)?

**Comment by tuurma** [comment]
Yes, of course. I forgot that dialects are not hypothesis-specific.

**Comment by Hippodamie** [comment]
Actually, they sometimes may be. But we did not plan to be able to show it. So, when it happens, we write a special note in the Onomastics column.

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/39761146-93e0e2c6-52d7-11e8-8c53-83a9bd61c866.png)

**Comment by tuurma** [comment]
Fixed display of significant relative name 

![image](https://user-images.githubusercontent.com/449468/39761637-ea5b914a-52d8-11e8-8259-f9c82302fd97.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

many thanks.
Could you, please, also, delete the Latin form of the name in the same 2nd line?
Τhank you also for the signficant relative name !
Best,
Sophie
