### ISSUE TITLE
Bug on Τheudagoras and questions about label and Root in the sub form window

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#382]
Dear Magdalena,

An important question, since we will have to make more complex lots of Roots in the subforms.

When a Root looks like that: θε(ο/ᾱ)- or like that : φρ(ο̄̆ν/α)-
what form have we to give to the label: does it have to be as close as possible of the Root?
I mean do we have to set a dash also for the label, like θεοᾱ- and φρο̄̆να-?
Or is it a problem for the system if we have as labels for θε(ο/ᾱ)- and φρ(ο̄̆ν/α)-, more simply:
θεο or even θε and φρο̄̆ν?

The question is: could we keep the label as it is currently (θε) and change only the Root into θε(ο/ᾱ)-?

Could you, please, fix Theudaogoras rather quickly, because I have to give back a paper and I have to put screenshots of the line of this name in my paper ?

Have a good week-end.
With all best wishes and thanks,
Sophie

**Comment by tuurma** [comment]
>Is necessarily the label exactly corresponding to the root:
>e.g. if the root is θε(ο/ᾱ), has the label to be θεοᾱ (with the same letters)?
>Diacritics like the macron on θεοᾱ are they ‘authorized’ by the system in the label, or do we have better to write: θεοα without the macron of the Root?
>Could we imagine to have as a label only : θε and as a root θε(ο/ᾱ)?
>In other words, how did you plan/understand ‘label’? How do you and/or will you use it in the system? >Does it only belong to the back office and was it conceived only to be sure not to disturb the machine with parasit signs as macron parentheses etc.?

The label is supposed to be understood as an identifier for the root, similar as people have eg. tax identification number. There are two reasons for it in our system:

1. The XML language specification only allows certain character ranges in identifiers, in particular parentheses () or / are prohibited
2. We can adjust freely the root without needing to update all the names that referred to it since an identifier will always stay the same

The identifiers are only used under the hood, so in the visualization or in print you will always get the correct root form. Thus you can use any shortened form for the label, only thing is to make sure they remain unique through the system.

![image](https://user-images.githubusercontent.com/449468/35039734-1133ea80-fb7f-11e7-9983-96ead3806f8d.png)

Looking at the list of roots you can clearly see that the root form can get shortened as you see fit to create a label, eg αν(δ)ρ to ανδρ or α(ν)/ν to simply αν  

Hope that answers your concerns!

**Comment by Hippodamie** [comment]
MERCI, Magdalena !!!

 What is your schedule for the following tasks ? Can it be done now, even if the system bugs a lot ?
Data export into CSV
Review and change tracking functionality
all best, but, please, could you help Gerard, who cannot search anymore because of Ajax (or complained about it at 12.50, maybe be you fixed it)
Sophie
