### ISSUE TITLE
Again a bug on Hesiodos : I had to re-enter. It is a difficult entry...

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#385]

**Comment by tuurma** [comment]
Currently the search works fine, including the Hesiodos entry. Nevertheless the indexes are clearly not stable and since it is not an application issue but rather a bug in the exist-db, I have to escalate it further to my colleagues. I will keep you posted on our findings but please bear with us as it is very difficult problem to diagnose.
