### ISSUE TITLE
Bold vs normal for high vs low hypotheses

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#39]
Since you put in bold the R1, R2, why not put them in bold (when high certainty) and let in normal for the low?
And the same in the columns Structure, Semantics, Lexis and Bibliography.

That is all for the moment.
Best,

Sophie

**Comment by tuurma** [comment]
same as #11, closing the other one

**Comment by tuurma** [comment]
Copying from #11 earlier remarks: 
For names with two or more linguistic interpretations as Αἰσχρύβης (see your interface), could it be possible to have the second interpretation (and third when it is) visible as lower, for example in grey color and not in black so that people directly see what is the more important interpretation
