### ISSUE TITLE
Hi, Magdalena: Ktesarchos and other in R κτᾱσ-: could you please give access to the sub-form? Many thanks, best, Sophie

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#391]

**Comment by Hippodamie** [comment]
Dear Magdalena,

Same trouble for μαραντ-. And no Save possible.

**Comment by tuurma** [comment]
Please note extraneous space after the root, which leads to problems. Since base forms are identifiers for morphemes, it is of importance they are matching *exactly* the form defined in morpheme list and they may not include whitespace

![image](https://user-images.githubusercontent.com/449468/36867024-3baabae6-1d94-11e8-830f-7a4bd74a0c6c.png)

I have found 49 occurrences of extra space in @baseForm attribute, will try to fix them.

**Comment by tuurma** [comment]
```xquery
xquery version "3.1";

declare namespace tei="http://www.tei-c.org/ns/1.0";

let $names-root:='/db/apps/lgpn-ling-data/data/names'

let $qs:='ἀνα*'

(:let $qs := replace(normalize-unicode($qs, "NFD"), "[\p{M}\p{Sk}]", ""):)
(::)
(:let $qs := $qs:)

(:return $qs:)
(:(::):)
(:for $i in collection($names-root)//tei:orth[ft:query(., $qs)]/ancestor::tei:entry :)
(: return $i//tei:orth:)
 
 for $i in collection($names-root)//tei:m[contains(@baseForm, ' ')]
 let $a:=normalize-space($i/@baseForm)
 return 
 update replace $i/@baseForm with $a
```

**Comment by tuurma** [comment]
Still 7 strange cases remains, please kindly review them

```
Φίλαργος
Ἀθηνοίτης
Ἀλκοίτας
῎Ανδροιτος
Ἀγανώ
ἈγροίταςἈργόφιλος
```

**Comment by Hippodamie** [comment]
I do it  tomorrow afternoon, because I have a working session tomorrow morning to prepare now,
good night,
all best,
Sophie
