### ISSUE TITLE
Suffix 1 -> Flexional morpheme 1

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#419]
resulting from #407 

* [ ] Rename in the visualization table

![image](https://user-images.githubusercontent.com/449468/39111626-1782e8a8-46d6-11e8-8ce0-c2aac496396d.png)

* [ ] Rename in the entry form

![image](https://user-images.githubusercontent.com/449468/39111683-4ff623e4-46d6-11e8-8c6c-5de15e4380df.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena,
Very well. Thank you !

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/LGPN-ling/commit/d3b563ffa4d1cbce9784c52327a95aa18f12b459

See on test server:  
http://admin.existsolutions.com:55221/exist/apps/lgpn-ling/editor.xhtml 
http://admin.existsolutions.com:55221/exist/apps/lgpn-ling/index.html

<img width="987" alt="bildschirmfoto 2018-04-26 um 14 32 35" src="https://user-images.githubusercontent.com/1157669/39306071-624f9b5c-495f-11e8-907b-d28786290193.png">

<img width="234" alt="bildschirmfoto 2018-04-26 um 14 32 08" src="https://user-images.githubusercontent.com/1157669/39306079-674f8982-495f-11e8-8548-85bd5865ac04.png">

**Comment by Hippodamie** [comment]
Perfect : thank you !

**Comment by tuurma** [comment]
Thank you Alexandra!
