### ISSUE TITLE
An ‘of’ to add to each item of the list called “significant relative name’

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#423]
Hi, Magdalena,

Could you please add now or/and in the new design for each item of the significant relative name list ‘of’, because it is currently totally ambiguous for us.
So we would like to read:
son of
daughter of
father of
mother of
woman of.

We have currently:
son 
daughter
father
mother
woman

I must say it is for everybody quite ambiguous  in lgpn2 and lgpn4 too (an ‘of’ would help everyone there too).

Many thanks in advance,
with all best wishes,
Sophie

**Comment by plutonik-a** [comment]
Hello @Hippodamie!  
I've updated the test server with your requested changes.  
See http://admin.existsolutions.com:55221/exist/apps/lgpn-ling/editor.xhtml

<img width="995" alt="bildschirmfoto 2018-04-26 um 12 51 28" src="https://user-images.githubusercontent.com/1157669/39301855-f01c9e6c-4950-11e8-97f7-2aae68c8c1d1.png">

**Question:**   
Could you please elaborate, where else you want to have the wording "[...] of" to be changed? I don't understand what "lgpn2" and "lgpn4" stands for.

**Comment by Hippodamie** [comment]
Ηello, Alexandra !

I do not understand, but the version of About LGPN (and its French equivalent) I see at the address below are NOT the versions I asked to set online. I gave the pdf forms and the word docs on GitHub. Almost all has been re-written and the docs have to be set online in the exact form I sent them.

See on GitHub #422.

For « of » many thanks, it is OK. For lgpn2 and 4 I spoke about the LGPN database, see http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn/index.html
see Relationsship (where f. and s. without of are ambiguous), but I did not spoke about it to our colleagues in Oxford :

**Comment by plutonik-a** [comment]
@Hippodamie   
In your comment above, you are referring to issue #422, but that issue is still open, so no wonder you can't see it completed on the test server.  
I'm working on my assigned tickets one by one today, so hopefully everything will be completed by today.  

I will comment in each issue after completion and ask for your approval, if I'm not sure, if I understood the requirements all right, because I'm not familiar with the underlying structure of your work requirements and sometimes specific termini. I hope, I don't bother you too much posting you about that.

>  I must say it is for everybody quite ambiguous in lgpn2 and lgpn4 too (an ‘of’ would help everyone there too).

>  see Relationsship (where f. and s. without of are ambiguous)

Ok, now I understand. That was an additional issue. I have checked on the URL you gave me, and I couldn't find the mentioned place in the form. Just found  

<img width="509" alt="bildschirmfoto 2018-04-26 um 13 37 03" src="https://user-images.githubusercontent.com/1157669/39303676-5a39d502-4957-11e8-963d-9563b4e88449.png">

which seems to be ok, but you said "f and s without 'of'", so could you open an issue in the correct repo and specify, where I will find the wording, please?

**Comment by Hippodamie** [comment]
Hi, Alexandra : what does mean #422 « is still open » ? Files (pdf+ word) I put there are ready to be online : they are the updated versions (French and English) of the current obsolete versions ‘About LGPN-Ling’. Could you, please, ask Magdalena to have access to the files of  #422 ?

For « of » , the below list is a little too complex for LGPN-Ling, but we will improve our current list by adding some of its items, thus we would like to have:
son of
daughter of
father of
mother of
woman of
parent of
relative of?

That would be perfect. And we need to keep in LGPN-Ling the current title ’Significant relative name’. 
Many thanks in advance.

Best,
Sophie

**Comment by plutonik-a** [comment]
Hi @Hippodamie, could you please verify and approve, if this issue is completed by checking the current state on our test server? URL: http://admin.existsolutions.com:55221/exist/apps/lgpn-ling/editor.xhtml

**Comment by Hippodamie** [comment]
Hi, Alexandra,

are missing in the current state of Foreword :
β
1)
2)
3)
4)
c.
d.
of the revisioned version.

And all that follows seems still to be the former version. Since we have almost re-written/updated every §, could you please make the substitution for each of them? 

Could you also please keep the bold as in the word and pdf revisioned version ? And it would look nicer if the end of lines on the right of the page was aligned as it is on the left side.

Thank you for your work.

Sophie

**Comment by plutonik-a** [comment]
@Hippodamie 
I assume, this task is done then and so it can be closed now. 

I will copy your last comment into issue #422 and paste in an answer there.
