### ISSUE TITLE
Our Skype on Wednesday October 17th

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#464]
Hi, Magdalena,

Here is the page to prepare our talk (same file doc.x or pdf).

Until wednesday,

all the best,
Sophie

[Skype Magdalena 17 octobre18.docx](https://github.com/eXistSolutions/LGPN-ling/files/2478908/Skype.Magdalena.17.octobre18.docx)
[Skype Magdalena 17 octobre18.pdf](https://github.com/eXistSolutions/LGPN-ling/files/2478909/Skype.Magdalena.17.octobre18.pdf)

**Comment by tuurma** [comment]
We've spoken on Wed Oct 17th for around 1.5h

We have discussed mid-term development for LGPN-Ling and agreed to 

## allocate around 5 days of work to create a first version (a prototype) of public-facing search for LGPN-Ling. We'll proceed in agile manner, so not creating very formal specification first but we'll start with requirements already gathered for editing interface and a number of requests already formulated (like leading wildcard searches etc). Main bulk of this work is planned for January 2018

## spend some time on improving the performance of our app and search so it can withstand increased load and growing dataset

## add most urgently needed features and address bugs as they appear

An invoice has been drafted to cover the work already delivered (around 64h) since our last billing and allocate funds towards the work outlined above.
