### ISSUE TITLE
A bug in the list I just spoke about, when adding a second hypothesis

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#523]
Dear Magdalena,

look at the list: quite incredible: the first elements of the list does not appear!
Could you please restore it?
It always happen for the list ONLY when we edit a second hypothesis.

Many thanks for your help,
with all bet wishes,
Sophie

![capture d ecran 2019-01-09 a 18 21 05](https://user-images.githubusercontent.com/16923546/50916350-379a5d00-143b-11e9-8878-dab6ed41c553.png)

**Comment by tuurma** [comment]
I can confirm this behaviour, both form markup and generated entry values are correct, unfortunately display labels are missing, due to the fact that &lt; mark occurs there. Bug lies on the side of betterforms so there's little I can do about it at the moment. I will ask my colleague for a workaround, if any exists.
