### ISSUE TITLE
display names using given lexeme

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#545]
Add a link to Lexemes list leading to the list of names using this lexeme - would speed up work on making Lexeme list more consistent

<img width="919" alt="image" src="https://user-images.githubusercontent.com/449468/57840766-8aa96580-77c9-11e9-9f54-4078196e9276.png">

**Comment by tuurma** [comment]
Dear Sophie @hippodamie

I have added a listing of all names using a given lexeme to the list, which should help you find the names and save a lot of time in cases like few previous issues reported. Hope you will find it useful. I'm sorry the page loads quite long (around 1 minute for me) and I will try to speed things up.

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/449468/57862552-d45d7480-77f8-11e9-936c-d00c5223410c.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

I spoke about it with Violeta at noon!!!! To ask you about it! 
You are incredible! Great! 
I do not know how to thank you!!!
Is it the reason why calling Lexems blocked a minute ago?
Hope you will find a solution to speed it…, because we all use Lexems every time!
So many thnaks: you change our lifes and especially Violeta’s life!
We are preparing the Searching interface building by clearing all the ID and checking the Bases.
It will help me also to better think about the requests of the Searching interface, before our Skype.

With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

a problem: it does not want anymore to delete…
But maybe you are still working on it.
Good luck and many thanks anyway,
with best wishes,
Sophie

**Comment by tuurma** [comment]
Deleting is now fixed, still working on making it faster.

**Comment by Hippodamie** [comment]
Thanks a lot, Magdalena,
have a good week-end, 
best,
Sophie

**Comment by tuurma** [comment]
In the end I've decided to split up Lexemes page into sub-lists - one for each letter, this helps loading things faster

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/449468/57920215-d415b580-789a-11e9-8843-672cc6f39f9d.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

perfect! Except that the numbers () does not seem to correspond to the real number of items. See eg (1)h etc.

Could I ask you for a little thing?

The following is wrong:




Could you, please, take off the spirit above α in the following 3 IDs?
So that we have απελλα
απολλο̄ν
απολλο̄νιο?

Many thanks in advance,
best 
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

sorry, I understand now the numbers! But visual is not good, since I made this mistake: space after () and not before, thus:

h(277)  ο̄(1) etc.

About the ordering:
ο̄ should be right after ο.
ϝ should be between ε and ζ.
ᾱ should be right after α.

Many thanks for that in advance,
with all best wishes,
Sophie

Anyway, it is GREAT!

**Comment by tuurma** [comment]
I'm sorry, I already fixed it in the morning but can't reach the server at the moment. On my local machine it looks like this. I will deploy it on the server when the connection works again.

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/449468/57940870-ae55d400-78cd-11e9-972a-cc790e9ea54c.png">

**Comment by Hippodamie** [comment]
It’s ok, as you see it yourself! I am myself on Chrome…

Could I ask you for a help on the following ID with 133 entries?



Could you please change the ID into αρχε (not αρκhε anymore)?

Many thanks if you can.
Have a good week-end,
best Sophie

**Comment by tuurma** [comment]
Updated the server just a moment ago, so the sorting and styling of the list of letters in Lexemes is looking better.

**Comment by Hippodamie** [comment]
Many thanks, dear Magdalena!

Could I ask you for parentheses () in the Suff.2 list?

Could you please add parentheses for currently: αδ ιδ transforming them into: (α)δ,   (ι)δ?

Man thanks in advance,
with all best wishes,
Sophie
