### ISSUE TITLE
A visualization bug on Boutalos

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#591]
Dear Magdalena,

look at that: how is it possible?

Could you please fix it?
Many thanks in advance,
with all best wishes,
Sophie
![Capture d’écran 2020-06-29 à 16 30 42](https://user-images.githubusercontent.com/16923546/86018363-879d2300-ba25-11ea-8d4c-f347b99057cd.png)

**Comment by tuurma** [comment]
Dear Sophie,

I looked at
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Boutalos
and
saw that the Root for secondary hypothesis was βουτ(ᾱ) while corresponding
lexeme should be βουτᾱ, which is why it didn't show up in the
visualization. Is that what you meant?

Magdalena

**Comment by Hippodamie** [comment]
Dear Magdalena,

I do not really understand what you mean:
what do you mean when you distinguish ‘Root’ βουτ(ᾱ) and ‘Lexem’ βουτᾱ?
We only have: Lexem and Constituent, isnt it?
And very often Constituent does not have the macron.
Do we speak about the same thing?
Sophie
