### ISSUE TITLE
Links between LGPN and LGPN-Ling search results

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#592]
Dear Magdalena,
1° starting from the joined screenshot, don't you think we could have:
under the current line of results for Ἀγαθοκλέα

the semantic analysis line of LGPN-Ling for this name, appearing automatically (or put a sign + beside Ἀγαθοκλέα, and if you click on +, you have the additional LGPN-Ling analysis appearing below)? And clicking on the name itself, as we currently can, we would get then the list of all persons bearing the name.

![Capture d’écran 2020-07-28 à 18 31 30](https://user-images.githubusercontent.com/16923546/88694043-4c634200-d100-11ea-917d-86cfed52944f.png)

2° It is more complicated if we search for *κλέα, since we will have several results. But same system: you put a + near each Greek name and clicking on +, we get the LGPN-Ling analysis; but clicking on the Greek name, we get the list of the persons.

So it could be a way for our data to be operated starting from LGPN.

The other way would be starting from LGPN-Ling own site.

Best,
Sophie

**Comment by Hippodamie** [comment]
The ideal will be to be able to switch from LGPN to LGPN-Ling site and back. The two sites being in permanent connection.

**Comment by Hippodamie** [comment]
In fact, we would like to be able to switch from LGPN-Ling to both sites (LGPN name Search and LGPN Database Search).

**Comment by tuurma** [comment]
Dear Sophie, to keep things simple and future-proof, I'd suggest

* as a first step
  * add small icons leading from LGPN Name search and Database search to LGPN-Ling (opening in a new browser window)
  * similar icon leading from LGPN Ling to LGPN
* as a second step
  * create an API for automated retrieval of information about a name from other systems so that Ling information can be displayed inside other websites, without the need to visit the original site
 * on Ling side, prepare a client (small software module) to consume similar API exposed by LGPN so we can display basic information from LGPN e.g. a popup window

Implementing the second step depends on our budget situation but for the interoperability and impact I'd strongly suggest making the effort. I expect LGPN Ling to become the canonical resource for identifying Greek names so many projects would probably use automated tools to help marking up occurrences of Ling names in their texts.

**Comment by Hippodamie** [comment]
Dear Magdalena,
yes, very well.
Could you please give an estimate for the second step?
Thank you in advance,
best,
Sophie

**Comment by tuurma** [comment]
Now we have links from the LGPN Name search, the Database search will be possible with the new version, which depends on Oxford funding  (unclear atm)

**Comment by Hippodamie** [comment]
ok, I understand.
Thank you for all;
