### ISSUE TITLE
Table column headings

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#626]
French

![image](https://user-images.githubusercontent.com/449468/135983597-23ce4e2b-ff6e-4002-9395-21fd6b5117a4.png)

English

![image](https://user-images.githubusercontent.com/449468/135983860-b637653a-bfa1-4f93-b55b-3eb642fced50.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena,

in the English version, last columns, same level as Lexis: not References but: Onomastics.
Thank you,
best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

do you remember I wrote this week asking to substitute Lexemes instead of Lexicon/Onomastics and in the last column Onomastics instead of References.
And in French, just to substitue Bases instead of Lexique/Onomastique.

And also substitute Morphosyntax, French Morphosyntaxe instead of Structure etc..

Many thanks for that too. I will read now the other emails.
