### ISSUE TITLE
Heading/logo and website title

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#627]
![image](https://user-images.githubusercontent.com/449468/135984323-c9248610-60cb-413d-aead-966cc3e6ae0b.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/135987601-b0077362-dff2-490c-ac48-55ef18447103.png)

![image](https://user-images.githubusercontent.com/449468/135987675-9b5ef75c-c9c1-4af6-91c8-18c0d5f87292.png)

@hippodamie please confirm the French wording

**Comment by Hippodamie** [comment]
Dear Magdalena,

perfect!
Best,
Sophie

**Comment by Hippodamie** [comment]
Hi, Magdalena,

in fact we did not need that in the white band where you set it. When I answered, I was on my email and did not understand where you would put it.
I think you just need now to work from the 2 last files I pasted on #621, which are quite short and just are about what is essential.
I explain there, among others, I would like the top menus and the top bands look like LGPN new Search prototype.
About design and titles changes, please, wait until we speak together before doing any change. Because for example, I did not ask, to have browse.name-Greek written like that, and repeated at everyline of this menu: it is enough to write browse only one time and at the top, where is currently written in French ‘Trier par’. And we do not need neither to have facets written like facets.hdialect, facets.morpheme. I had explained what we need at these places: Dialect-Areal1; Bases instead Lexemes or now morphemes and then Constituents. And beside: Top50, which would be perfect in both languages.
Many thanks in advance,
best ,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/136032497-af779cdd-c924-4f81-a27c-51b28979b78c.png)
![image](https://user-images.githubusercontent.com/449468/136032571-3658f57c-af43-43d0-b996-0498703275d3.png)

**Comment by Hippodamie** [comment]
it looks wonderful, exactly what we would like! Thank you!

**Comment by Hippodamie** [comment]
Could the function reset still exist in this new design (clicking for example on the olive leaf around the left corner as it was in the previous design)?

**Comment by tuurma** [comment]
Yes, the name of the project redirects to the start page, this is typical use pattern in websites.
