### ISSUE TITLE
Feed-back 2 (without Classification which is still in progress

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#655]
Here is the second part of the feed-back.
Classification, if it goes as I hope, will follow tonight.
Have a nice sunday.
Thank you for ghost names and the rest.
with all best wishes,
Sophie
[Feed-back 2022_01_23 (part 2).docx](https://github.com/eXistSolutions/LGPN-ling/files/7920115/Feed-back.2022_01_23.part.2.docx)

**Comment by tuurma** [comment]
Dear Sophie, could you please NOT send me word files but put your remarks directly here? It makes my life extremely hard to search through dozens of files and not be able to reply in thread like we can do here in the comments. Thank you.

**Comment by tuurma** [comment]
## From the file: Feed-back 2022 January 23

> Could additions of About LGPN-Ling etc. be as easily made after transfer?

Yes. I have just added the old versions but these need definitely to be changed.

I would suggest dividing the "About" text into smaller parts

* Introduction: a brief text that would welcome everyone on the start page
* Credits: for project members and thanks
* About the edition: where you discuss the actual subject like is now done in Foreword
* How to use the interface

> A2. About Edition:

> a) Is the cross in the square made to delete a name?
> b) How do we edit a new name?

Yes. This is not fully functional yet, I am working on it. There will be an "Add" button in the menu for editing new names.

> c) for Prefix, we will not have anything else than Adv: so the list is not necessary. Could you, please, delete the others?

At the moment I would leave it as is and return to this if we have time left.


> B. Classification

* Complex
  - primary / primaires
  - derived / dérivés
  - truncated / tronqués
  - shortened / raccourcis
* Simple
  - primary
  - derived 
  - truncated


C. Other facets
1. Multiareal appears if we click on a label. Why shall we have it? It is confusing. Could we not see it anymore?
> 2. Suffixes order: which kind of logic in this order (in both facets, also suffix in position)? The ordering should be that of the big list in the editor (alphabetical order or by decreasing frequence).


3. For the reordering of certain of the facets (and deletion of some of the last ones), see File Feed-back 1 #654.


D. Others

![image](https://user-images.githubusercontent.com/449468/150816646-87887224-3100-4dca-9ecb-7e401dab9495.png)

I have no idea where it is. Please, you need to provide me with context otherwise I can't help. Do you see it in a particular name or lexeme? If yes, which one? It is easiest to give me a link to the page.

3. Catalogues:

### Lexemes and Meanings

**It is very important that the ID field does NOT contain spaces, parentheses (), dots ., commas, colons and other special characters. You may use underscore character _**

If you report an issue, please copy the id of the lexeme and not just a screenshot, otherwise it is very hard to find the entry you have trouble with. 

> In fact, Μοκαπολις has its own meaning whitout parentheses. I do not know how to make disappear this one, which should not be associated anymore with μουκα. Could you, please, delete it?

You also need to tell me clearly if I am supposed to delete a name or lexeme or the association. This is something you can easily do yourself too, so perhaps it is counterproductive to ask me.

> c) For this one, could you please substitute mummy_nurse and delete the (good) etc. meaning? I cannot manage with this one. Thank you very much.

Again, there should not be () in the ID. You can use it in French and English meanings but NEVER in id field.

**Comment by Hippodamie** [comment]
Dear Magdalena,

I will improve that on Wednesday. Sorry if it was not clear. Thank you also for the other email on sorting suffix etc. 
Good evening,
all best,
Sophie

**Comment by Hippodamie** [comment]
I begin with that message of you.
1. I will rewrite (simplify) the “About” + How to Search (which was quite ready, but has to be up-dated with the new facets status. 
2. Alcmeon macron on suffix, see
 https://apps5test.existsolutions.com/exist/apps/lgpn-ling7/index.html?filter=%CE%B1%CE%BB%CE%BA%CE%BC%CE%B1%CF%89%CE%BD&filterBy=name
That's it. I will now answer to your last message.
