### ISSUE TITLE
A substitution of antiques to current anciens in the end of the title of the project LGPN-Ling

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#662]
Dear Magdalena,

I realize that antiques in French is necessary, and not current ‘anciens’, which is not precise enough (different in English).
Could you please make the substitution?
Sorry and thanks a lot,
best,
Sophie

**Comment by Hippodamie** [comment]
Another thing: 
could you please add in small under LGPN-Ling etc.
Project director: Sophie Minon

**Comment by tuurma** [comment]
Dear Sophie,

in my opinion adding the "Project director..." in the site header is not ideal, will take up the screen space we rather need and is not really a common practice (see, e.g. LGPN website).

I'd suggest adding this information in the site footer perhaps and above all restructuring slightly the "About the project" and "Team" subpages so that your name and status as the director is right on top of both these. Now it seems a bit weird that the "Team" page starts with listing of LGPN team in 2013 and not your own ;-)

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/449468/191955734-2c14e77f-4a1b-48dc-aad9-b22cb8a159ab.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

ok for the first §.
Of course, please, do not forget anybody photo: some are currently missing (Matilde, Florian, Dan Dan and Enrique: look at my pretty first slide!!!

About:
> Now it seems a bit weird that the "Team" page starts with listing of LGPN team in 2013 and not your own ;-)

OK: you could change the order of the currently 4 §§: in the following new order:
3 LGPN-Ling is directed etc.
1 The project
2
4 To all of those scholars and institutions

Thank you for what you already did!

Best,
Sophie

**Comment by tuurma** [comment]
Ok, I will reorder.

Regarding the photos, they are all visible for me, perhaps you need to refresh the page (Shift+Reload button)

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/449468/192014023-94ba5013-5f42-41b9-b94d-8d2b05682f5a.png">
