### ISSUE TITLE
Place of gender label for variants

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#695]
Dear Magdalena,

now, instead of its previous place, gender label comes on the right of Geolinguistics, like:
![Capture d’écran 2022-07-11 à 22 41 24](https://user-images.githubusercontent.com/16923546/178354402-12427846-b664-4823-9f46-7341d043012a.png)
Could we please have it rather on the left: it looks clearer, look at that:
![Capture d’écran 2022-07-11 à 22 44 05](https://user-images.githubusercontent.com/16923546/178354837-8edc2a70-1fa1-46a6-9cd7-823b3711c3ab.png)
Ιt is confusing when the Geolinguistic label is long.

Could you please put it back at its previous place?
Thank you in advance,
best,
Sophie

**Comment by tuurma** [comment]
It has been to the right of Geolinguistics also before. It is a bit close only in relatively rare cases when Geolinguistics label contains a lot of text, in most cases there's a clearer separation.

I wouldn't like to move it to the left of Geolinguistics because then we'd need a separate column, while as it is, I am "stealing" the space under "Bases" which is never used for name variants.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/449468/191983016-b85499e6-79ba-44b2-a10a-6aeeee0d1ddf.png">

**Comment by Hippodamie** [comment]
OK!
