### ISSUE TITLE
A Base missing in the indexation of the corresponding facet

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#700]
Dear Magdalena,

I was Main Searching all names with a στρατο Base; then, I went through all linked bases through the facet Bases (function More). But there was at least one Base missing, a very current one: αγαθο!

How is it possible? Is the list of Bases not exhaustive?
I could get it finally by the Lexicon connections facet.
![Capture d’écran 2022-09-24 à 11 33 16](https://user-images.githubusercontent.com/16923546/192091010-a4702557-bed4-4f1e-abad-a6ce5e1cfc0b.png)

I think one of the most current search users will do is exactly of this type: they will work on compound names, which are the most exciting, and so will combine Main filter and Bases facet, to look at the different combinations attested.

So it is an important subject.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
I know where the problem is: you'd expect to see *all* the lexeme bases  available for "στρατο". But facets by default show you only up to a fixed number (in our case 10 or 100) most frequent values for what you searched. Therefore obviously when you filter by "στρατο" the most common base is "στρα-τ(ο)" with 208 matches, next is "σα(ϝ)(ο)" with 9 and so on...

https://lgpn-ling.huma-num.fr/exist/apps/lgpn-ling7/index.html?filter=%CF%83%CF%84%CF%81%CE%B1%CF%84%CE%BF&filterBy=morpheme-root

<img width="236" alt="image" src="https://user-images.githubusercontent.com/449468/195077786-824e3741-aa2c-4025-a84f-c0b15960a74f.png">

Even when selecting "plus" it would only show 100 most frequent, not all of them, this was why you could not find "αγαθ(ο)" which only had one match. I know that other visible options might only have one match as well which led to the confusion.

Therefore I did change the algorithm showing "more" options to show **all** available values. The list can get very long, particularly for bases, so I did add a scroll bar to each of the facets. I think it is now more intuitive and gives fuller insight into the situation.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/449468/195078021-44c291e5-de25-4477-9a5b-faded295ed32.png">
