### ISSUE TITLE
Cleaning the http address to quote?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#720]
Dear Magdalena,

is it necessary that the http address given in the last column at right, with the last up-date date, is so long and difficult? Would it be possible to see something cleaner, shorter and easier to quote, copy and so on?

All best,
Sophie

**Comment by tuurma** [comment]
We have this citation button, which atm allows to copy this shortened phrase and links to an individual name page:

>  LGPN-Ling, Aba, [https://lgpn-ling.huma-num.fr/exist/apps/lgpn-ling7/Aba] last updated: 2022-11-16

We could ask Huma-Num to configure the server so that the middle part `exist/apps/lgpn-ling7` is no longer necessary, but on my side I've done what was possible to make it short and human-readable.

**Comment by Hippodamie** [comment]
Shall I ask or is it better you ask?
