### ISSUE TITLE
Links to LGPN names and persons bearing the name: starting from Yanne's remark on Hierotimos

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#740]
Dear Magdalena,

about the problem of linking, I try to explain what happens. Hierotimos headname is indeed THE example, look at it on the site:
This headname does exist on LGPN Database (2 occ. LGPN3a). A wrong Ἱεροτιάδης has been edited in LGPN5c (which is currently not in Database) and I edited it inside LGPN-Ling Hierotimos' record, as being wrong in LGPN (in the special box) and having to be corrected as Hierotimos (thus, according to my proposal, we have now in fact 3 occ. of Hierotimos name).

Currently, when you click on LGPN or Magnifying glass, you arrive on ‘zero result’ (ιεροτιαδης) in both LGPN Name and Database Search, which is indeed logical.  But we need the LGPN link to the headname above all: fortunately, we have it by clicking on Trismegistos! Do you think it could be enough like that?

I must say that what would be **a major improvement** would be that:
clicking on each variant, we get each of them on LGPN Name Search; after we could go, from Name Search, to LGPN Search Database. 

What do you think? I was already told that it was a pity that we do not have the variants linked...
Could you work on that issue? Maybe letting away the special cases like Hierotimos, since Trismegistos link could be enough?
With all best wishes and thanks,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

one thing that was very easy to add was linking from each of the name variants to LGPN and Trismegistos searches

<img width="424" alt="image" src="https://user-images.githubusercontent.com/449468/219880169-65fe6d51-1a71-4dcd-9744-6125f7c7e8f3.png">

Regarding our guy Hierotiades, what is edited in the LGPN field is the name is `Ἱεροτιάδης?` (with a question mark). This question mark is why linking fails, because the actual canonical name in LGPN is obviously recorded as `Ἱεροτιάδης`, it only appears with a question mark after to show uncertainty. See the links below which correctly show Hierotiades in LGPN.

http://clas-lgpn5.classics.ox.ac.uk:8080/exist/apps/lgpn1-search/index.html?name=%E1%BC%B9%CE%B5%CF%81%CE%BF%CF%84%CE%B9%CE%AC%CE%B4%CE%B7%CF%82

http://clas-lgpn2.classics.ox.ac.uk/cgi-bin/lgpn_search.cgi?name=%E1%BF%BE%CE%99%CE%B5%CF%81%CE%BF%CF%84%CE%B9%CE%AC%CE%B4%CE%B7%CF%82

So, in this case I believe the answer is to edit the LGPN name field in LGPN-Ling.

**Comment by tuurma** [comment]
Regarding `Ἱεροτιάδης` again, in LGPN-Ling it was entered with a different initial character than in LGPN, so the Database search (which is sensitive to accents) failed.

In LL we had `Ἱ` (Greek capital Iota with Dasia) and not as in LGPN `῾Ι` (two separate characters, modifier character Dasia and Iota). I corrected to match LGPN version.

**Comment by Hippodamie** [comment]
Dear Magdalena,

you mean by your last sentence (So, in this case I believe the answer is to edit the LGPN name field in LGPN-Ling) that we have to edit the LGPN name in the LGPN field without its question mark?
Do I understand correctly?
All best,
Sophie
