### ISSUE TITLE
Column Lexis: 'cf. also' is a problem

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#92]
In that column, we should have Cf. (and not 'Cf. also) before the quotation, nothing before DELG.
![screen shot 2016-02-03 at 14 08 49](https://cloud.githubusercontent.com/assets/16817615/12784768/0102e35e-ca81-11e5-8aee-9d8576a10123.png)

**Comment by tuurma** [comment]
Fixed this, though please note that in case of Againetos there's still Cf in this column, but this is because it was entered in the form and needs to be fixed there
![screenshot 143](https://cloud.githubusercontent.com/assets/449468/13189693/c70402dc-d750-11e5-80e8-309fd2821cb9.png)

![screenshot 144](https://cloud.githubusercontent.com/assets/449468/13189695/c706bfb8-d750-11e5-8de0-99173fea22bb.png)
